export default [
  {
    ref: '2MG-Ia-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Circles and composite figures, and one-direction translations of shapes.',
    competency: 'Represent and describe circles, half circles and quarter circles.',
    performance_standard: 'Compose, describe, and move shapes to model objects and spatial changes in everyday settings.',
  },
  {
    ref: '2MG-Ia-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Circles and composite figures, and one-direction translations of shapes.',
    competency: 'Compose and decompose composite figures made up of squares, rectangles, triangles, circles, half circles, and quarter circles, using cut-outs and square grids.',
    performance_standard: 'Compose, describe, and move shapes to model objects and spatial changes in everyday settings.',
  },
  {
    ref: '2MG-Ib-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Circles and composite figures, and one-direction translations of shapes.',
    competency: 'Describe and draw the effect of a one-direction multi-step slide (or translation) in basic shapes and figures.',
    performance_standard: 'Compose, describe, and move shapes to model objects and spatial changes in everyday settings.',
  },
  {
    ref: '2NA-Ic-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000, addition, ordinal numbers, and Philippine money up to ₱1 000.',
    competency: 'Count up to 1000.',
    performance_standard: 'Use whole numbers, addition, position, and money to solve everyday quantitative problems.',
  },
  {
    ref: '2NA-Id-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000, addition, ordinal numbers, and Philippine money up to ₱1 000.',
    competency: 'Read and write numerals up to 1000.',
    performance_standard: 'Use whole numbers, addition, position, and money to solve everyday quantitative problems.',
  },
  {
    ref: '2NA-Ie-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000, addition, ordinal numbers, and Philippine money up to ₱1 000.',
    competency: 'Recognize and represent numbers up to 1000 using a variety of concrete and pictorial models, and numerals.',
    performance_standard: 'Use whole numbers, addition, position, and money to solve everyday quantitative problems.',
  },
  {
    ref: '2NA-If-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000, addition, ordinal numbers, and Philippine money up to ₱1 000.',
    competency: 'Count by 2s, 5s, 10s, 20s, 50s, and 100s (not beyond 1000).',
    performance_standard: 'Use whole numbers, addition, position, and money to solve everyday quantitative problems.',
  },
  {
    ref: '2NA-If-2',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000, addition, ordinal numbers, and Philippine money up to ₱1 000.',
    competency: 'Order numbers up to 1000 from smallest to largest, and vice versa.',
    performance_standard: 'Use whole numbers, addition, position, and money to solve everyday quantitative problems.',
  },
  {
    ref: '2NA-Ig-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000, addition, ordinal numbers, and Philippine money up to ₱1 000.',
    competency: 'Describe the position of objects using ordinal numbers up to 20th.',
    performance_standard: 'Use whole numbers, addition, position, and money to solve everyday quantitative problems.',
  },
  {
    ref: '2NA-Ig-2',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000, addition, ordinal numbers, and Philippine money up to ₱1 000.',
    competency: 'Determine: a. the place value of a digit in a 3-digit number b. the value of a digit c. the digit of a number, given its place value.',
    performance_standard: 'Use whole numbers, addition, position, and money to solve everyday quantitative problems.',
  },
  {
    ref: '2NA-Ih-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000, addition, ordinal numbers, and Philippine money up to ₱1 000.',
    competency: 'Illustrate addition of 2-digit and by 1-digit numbers as “counting up” on the number line.',
    performance_standard: 'Use whole numbers, addition, position, and money to solve everyday quantitative problems.',
  },
  {
    ref: '2NA-Ih-2',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000, addition, ordinal numbers, and Philippine money up to ₱1 000.',
    competency: 'Add numbers with sums up to 1000 in expanded form.',
    performance_standard: 'Use whole numbers, addition, position, and money to solve everyday quantitative problems.',
  },
  {
    ref: '2NA-Ih-3',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000, addition, ordinal numbers, and Philippine money up to ₱1 000.',
    competency: 'Add numbers with sums up to 1000, with or without regrouping.',
    performance_standard: 'Use whole numbers, addition, position, and money to solve everyday quantitative problems.',
  },
  {
    ref: '2NA-Ii-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000, addition, ordinal numbers, and Philippine money up to ₱1 000.',
    competency: 'Illustrate and apply the following properties of addition using sums up to 1000: a. the sum of zero and any number is equal to the number b. changing the order of the addends does not change the sum c. changing the grouping of the addends does not change the sum.',
    performance_standard: 'Use whole numbers, addition, position, and money to solve everyday quantitative problems.',
  },
  {
    ref: '2NA-Ii-2',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000, addition, ordinal numbers, and Philippine money up to ₱1 000.',
    competency: 'Determine and write the value of a number of bills, or a number of coins, or a combination of bills and coins up to ₱1000 (centavo coins only, peso coins only, peso bills only, combined peso coins and peso bills).',
    performance_standard: 'Use whole numbers, addition, position, and money to solve everyday quantitative problems.',
  },
  {
    ref: '2NA-Ij-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000, addition, ordinal numbers, and Philippine money up to ₱1 000.',
    competency: 'Compare the values of different denominations of peso coins and bills up to ₱1000.',
    performance_standard: 'Use whole numbers, addition, position, and money to solve everyday quantitative problems.',
  },
  {
    ref: '2NA-Ij-2',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000, addition, ordinal numbers, and Philippine money up to ₱1 000.',
    competency: 'Solve problems involving addition with sums up to 1000, including problems involving money, with and without regrouping.',
    performance_standard: 'Use whole numbers, addition, position, and money to solve everyday quantitative problems.',
  },
  {
    ref: '2MG-IIa-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Measurement and estimation of length and distance in meters and centimeters.',
    competency: 'Measure and compare lengths of objects, in meters (m) or centimeters (cm), and distance in meters, using appropriate measuring tools.',
    performance_standard: 'Select tools and metric units to estimate, measure, compare, and solve practical length and distance problems.',
  },
  {
    ref: '2MG-IIa-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Measurement and estimation of length and distance in meters and centimeters.',
    competency: 'Identify and use the appropriate unit (m or cm) to measure the length of an object and the distance between two locations.',
    performance_standard: 'Select tools and metric units to estimate, measure, compare, and solve practical length and distance problems.',
  },
  {
    ref: '2MG-IIb-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Measurement and estimation of length and distance in meters and centimeters.',
    competency: 'Estimate length using meters or centimeters, and distance using meters.',
    performance_standard: 'Select tools and metric units to estimate, measure, compare, and solve practical length and distance problems.',
  },
  {
    ref: '2MG-IIb-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Measurement and estimation of length and distance in meters and centimeters.',
    competency: 'Solve problems involving length and distance.',
    performance_standard: 'Select tools and metric units to estimate, measure, compare, and solve practical length and distance problems.',
  },
  {
    ref: '2NA-IIc-1',
    domain: 'Number and Algebra',
    content_standard: 'Subtraction up to 1 000, increasing and decreasing patterns, and foundations of multiplication.',
    competency: 'Illustrate subtraction of 2-digit by 1-digit on the number line and as an inverse of addition.',
    performance_standard: 'Use subtraction, patterns, and equal groups to solve familiar real-life problems.',
  },
  {
    ref: '2NA-IIc-2',
    domain: 'Number and Algebra',
    content_standard: 'Subtraction up to 1 000, increasing and decreasing patterns, and foundations of multiplication.',
    competency: 'Subtract numbers where both numbers are less than 100 with regrouping: a. 2-digit minus 1-digit numbers b. 2-digit minus 2-digit numbers.',
    performance_standard: 'Use subtraction, patterns, and equal groups to solve familiar real-life problems.',
  },
  {
    ref: '2NA-IIc-3',
    domain: 'Number and Algebra',
    content_standard: 'Subtraction up to 1 000, increasing and decreasing patterns, and foundations of multiplication.',
    competency: 'Solve problems (given orally or in pictures) involving subtraction where both numbers are less than 100, with and without regrouping.',
    performance_standard: 'Use subtraction, patterns, and equal groups to solve familiar real-life problems.',
  },
  {
    ref: '2NA-IIc-4',
    domain: 'Number and Algebra',
    content_standard: 'Subtraction up to 1 000, increasing and decreasing patterns, and foundations of multiplication.',
    competency: 'Subtract numbers, where both numbers are less than 1000, with and without regrouping.',
    performance_standard: 'Use subtraction, patterns, and equal groups to solve familiar real-life problems.',
  },
  {
    ref: '2NA-IIc-5',
    domain: 'Number and Algebra',
    content_standard: 'Subtraction up to 1 000, increasing and decreasing patterns, and foundations of multiplication.',
    competency: 'Solve 1- and 2-step problems involving subtraction where both numbers are less than 1000 (including problems involving money), with and without regrouping.',
    performance_standard: 'Use subtraction, patterns, and equal groups to solve familiar real-life problems.',
  },
  {
    ref: '2NA-IIc-6',
    domain: 'Number and Algebra',
    content_standard: 'Subtraction up to 1 000, increasing and decreasing patterns, and foundations of multiplication.',
    competency: 'Determine the next term/s in increasing or decreasing patterns, e.g., numbers, letters and rhythmic properties, visual elements in arts, and repetitions.',
    performance_standard: 'Use subtraction, patterns, and equal groups to solve familiar real-life problems.',
  },
  {
    ref: '2NA-IIc-7',
    domain: 'Number and Algebra',
    content_standard: 'Subtraction up to 1 000, increasing and decreasing patterns, and foundations of multiplication.',
    competency: 'Create increasing or decreasing patterns.',
    performance_standard: 'Use subtraction, patterns, and equal groups to solve familiar real-life problems.',
  },
  {
    ref: '2SP-IIh-1',
    domain: 'Statistics and Probability',
    content_standard: 'Presentation and interpretation of data in tables and scaled pictographs.',
    competency: 'Present raw data, or data in tabular form, in a pictograph with a scale, or vice versa.',
    performance_standard: 'Represent and interpret everyday data using tables and pictographs with appropriate scales.',
  },
  {
    ref: '2SP-IIh-2',
    domain: 'Statistics and Probability',
    content_standard: 'Presentation and interpretation of data in tables and scaled pictographs.',
    competency: 'Interpret data in tabular form and in a pictograph with or without a scale.',
    performance_standard: 'Represent and interpret everyday data using tables and pictographs with appropriate scales.',
  },
  {
    ref: '2NA-IIi-1',
    domain: 'Number and Algebra',
    content_standard: 'Subtraction up to 1 000, increasing and decreasing patterns, and foundations of multiplication.',
    competency: 'Count the number of concrete objects in a group by repeated addition and create equal groups, using language such as “5 groups of 3” and “5 threes”.',
    performance_standard: 'Use subtraction, patterns, and equal groups to solve familiar real-life problems.',
  },
  {
    ref: '2NA-IIj-1',
    domain: 'Number and Algebra',
    content_standard: 'Subtraction up to 1 000, increasing and decreasing patterns, and foundations of multiplication.',
    competency: 'Illustrate and write multiplication as repeated addition, using a variety of concrete and pictorial models and numerals, and using: a. groups of equal quantities b. Arrays c. counting by multiples d. equal jumps on a number line.',
    performance_standard: 'Use subtraction, patterns, and equal groups to solve familiar real-life problems.',
  },
  {
    ref: '2NA-IIIa-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication, division, even and odd numbers, and unit and similar fractions.',
    competency: 'Multiply numbers using the 2, 3, 4, 5, and 10 multiplication tables.',
    performance_standard: 'Apply multiplication, division, and fractions to sharing, grouping, and other everyday situations.',
  },
  {
    ref: '2NA-IIIb-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication, division, even and odd numbers, and unit and similar fractions.',
    competency: 'Solve multiplication problems using the 2, 3, 4, 5, and 10 multiplication tables, including problems involving money.',
    performance_standard: 'Apply multiplication, division, and fractions to sharing, grouping, and other everyday situations.',
  },
  {
    ref: '2NA-IIIb-2',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication, division, even and odd numbers, and unit and similar fractions.',
    competency: 'Illustrate division through equal distribution of a number of objects into several groups.',
    performance_standard: 'Apply multiplication, division, and fractions to sharing, grouping, and other everyday situations.',
  },
  {
    ref: '2NA-IIIc-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication, division, even and odd numbers, and unit and similar fractions.',
    competency: 'Illustrate and write division expressions using a variety of concrete and pictorial models and numerals, in modelling division as: a. equal sharing or formation of equal groups of objects b. repeated subtraction.',
    performance_standard: 'Apply multiplication, division, and fractions to sharing, grouping, and other everyday situations.',
  },
  {
    ref: '2NA-IIIc-2',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication, division, even and odd numbers, and unit and similar fractions.',
    competency: 'Divide numbers using the 2, 3, 4, 5, and 10 multiplication tables.',
    performance_standard: 'Apply multiplication, division, and fractions to sharing, grouping, and other everyday situations.',
  },
  {
    ref: '2NA-IIId-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication, division, even and odd numbers, and unit and similar fractions.',
    competency: 'Find the missing number in a number sentence involving multiplication or division by 2, 3, 4, 5, and 10.',
    performance_standard: 'Apply multiplication, division, and fractions to sharing, grouping, and other everyday situations.',
  },
  {
    ref: '2NA-IIId-2',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication, division, even and odd numbers, and unit and similar fractions.',
    competency: 'Distinguish even and odd numbers using division by 2.',
    performance_standard: 'Apply multiplication, division, and fractions to sharing, grouping, and other everyday situations.',
  },
  {
    ref: '2NA-IIId-3',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication, division, even and odd numbers, and unit and similar fractions.',
    competency: 'Solve division problems using the 2, 3, 4, 5, and 10 multiplication tables, including problems involving money.',
    performance_standard: 'Apply multiplication, division, and fractions to sharing, grouping, and other everyday situations.',
  },
  {
    ref: '2NA-IIIe-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication, division, even and odd numbers, and unit and similar fractions.',
    competency: 'Represent and identify unit fractions with denominators 2, 3, 4, 5, 6, and 8.',
    performance_standard: 'Apply multiplication, division, and fractions to sharing, grouping, and other everyday situations.',
  },
  {
    ref: '2NA-IIIe-2',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication, division, even and odd numbers, and unit and similar fractions.',
    competency: 'Read and write unit fractions in fraction notation.',
    performance_standard: 'Apply multiplication, division, and fractions to sharing, grouping, and other everyday situations.',
  },
  {
    ref: '2NA-IIIf-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication, division, even and odd numbers, and unit and similar fractions.',
    competency: 'Order unit fractions from smallest to largest, and vice versa.',
    performance_standard: 'Apply multiplication, division, and fractions to sharing, grouping, and other everyday situations.',
  },
  {
    ref: '2NA-IIIf-2',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication, division, even and odd numbers, and unit and similar fractions.',
    competency: 'Represent and identify similar fractions with denominators 2, 3, 4, 5, 6, and 8 using groups of objects, fraction charts, fraction tiles, and the number line.',
    performance_standard: 'Apply multiplication, division, and fractions to sharing, grouping, and other everyday situations.',
  },
  {
    ref: '2NA-IIIg-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication, division, even and odd numbers, and unit and similar fractions.',
    competency: 'Read and write similar fractions in fraction notation.',
    performance_standard: 'Apply multiplication, division, and fractions to sharing, grouping, and other everyday situations.',
  },
  {
    ref: '2NA-IIIg-2',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication, division, even and odd numbers, and unit and similar fractions.',
    competency: 'Order similar fractions from smallest to largest, and vice versa.',
    performance_standard: 'Apply multiplication, division, and fractions to sharing, grouping, and other everyday situations.',
  },
  {
    ref: '2MG-IIIg-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Duration, clock time, lines, surfaces, and perimeter of plane figures.',
    competency: 'Describe the duration of an event in terms of number of days and/or weeks using a calendar.',
    performance_standard: 'Use time and geometric measurement to plan schedules and measure boundaries in real-life contexts.',
  },
  {
    ref: '2MG-IIIh-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Duration, clock time, lines, surfaces, and perimeter of plane figures.',
    competency: 'Read and write time in hours and minutes, with a.m. and p.m., using an analog clock.',
    performance_standard: 'Use time and geometric measurement to plan schedules and measure boundaries in real-life contexts.',
  },
  {
    ref: '2MG-IIIi-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Duration, clock time, lines, surfaces, and perimeter of plane figures.',
    competency: 'Solve problems involving elapsed time (minutes in an hour, hours in a day, days in a week), including timetables.',
    performance_standard: 'Use time and geometric measurement to plan schedules and measure boundaries in real-life contexts.',
  },
  {
    ref: '2MG-IIIi-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Duration, clock time, lines, surfaces, and perimeter of plane figures.',
    competency: 'Identify and explain the difference between straight and curved lines, and flat and curved surfaces of 3-dimensional objects.',
    performance_standard: 'Use time and geometric measurement to plan schedules and measure boundaries in real-life contexts.',
  },
  {
    ref: '2MG-IIIi-3',
    domain: 'Measurement and Geometry',
    content_standard: 'Duration, clock time, lines, surfaces, and perimeter of plane figures.',
    competency: 'Identify and measure the perimeter of a plane figure using appropriate tools.',
    performance_standard: 'Use time and geometric measurement to plan schedules and measure boundaries in real-life contexts.',
  },
  {
    ref: '2MG-IIIj-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Duration, clock time, lines, surfaces, and perimeter of plane figures.',
    competency: 'Find the perimeter of triangles, squares, and rectangles.',
    performance_standard: 'Use time and geometric measurement to plan schedules and measure boundaries in real-life contexts.',
  },
  {
    ref: '2MG-IIIj-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Duration, clock time, lines, surfaces, and perimeter of plane figures.',
    competency: 'Solve problems involving the perimeter of triangles, squares, and rectangles.',
    performance_standard: 'Use time and geometric measurement to plan schedules and measure boundaries in real-life contexts.',
  },
]
