export default [
  {
    ref: '6MG-Ia-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Tessellations and transformations involving translation, reflection, and rotation.',
    competency: 'Explore whether or not a shape tessellates.',
    performance_standard: 'Create tessellations and use transformations to model patterns and spatial changes in real-life designs.',
  },
  {
    ref: '6MG-Ia-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Tessellations and transformations involving translation, reflection, and rotation.',
    competency: 'Tessellate a surface using different shapes, including triangles, squares, and rectangles.',
    performance_standard: 'Create tessellations and use transformations to model patterns and spatial changes in real-life designs.',
  },
  {
    ref: '6MG-Ib-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Tessellations and transformations involving translation, reflection, and rotation.',
    competency: 'Draw resulting images of shapes that undergo translation, reflection, rotation.',
    performance_standard: 'Create tessellations and use transformations to model patterns and spatial changes in real-life designs.',
  },
  {
    ref: '6NA-Ic-1',
    domain: 'Number and Algebra',
    content_standard: 'Operations with decimals and fractions, and ratios.',
    competency: 'Add and subtract decimals with decimal parts of up to 4 decimal places.',
    performance_standard: 'Use decimals, fractions, and ratios to solve multi-step financial and quantitative problems.',
  },
  {
    ref: '6NA-Ic-2',
    domain: 'Number and Algebra',
    content_standard: 'Operations with decimals and fractions, and ratios.',
    competency: 'Solve multi-step problems involving addition and/or subtraction of decimals, including problems involving money.',
    performance_standard: 'Use decimals, fractions, and ratios to solve multi-step financial and quantitative problems.',
  },
  {
    ref: '6NA-Id-1',
    domain: 'Number and Algebra',
    content_standard: 'Operations with decimals and fractions, and ratios.',
    competency: 'Mentally multiply decimals of up to 2 decimal places by 0.1, 0.01, 0.001, 10, 100, and 1000.',
    performance_standard: 'Use decimals, fractions, and ratios to solve multi-step financial and quantitative problems.',
  },
  {
    ref: '6NA-Id-2',
    domain: 'Number and Algebra',
    content_standard: 'Operations with decimals and fractions, and ratios.',
    competency: 'Solve multi-step problems involving multiplication of decimals that may or may not also involve addition or subtraction of decimals, including problems involving money.',
    performance_standard: 'Use decimals, fractions, and ratios to solve multi-step financial and quantitative problems.',
  },
  {
    ref: '6NA-Ie-1',
    domain: 'Number and Algebra',
    content_standard: 'Operations with decimals and fractions, and ratios.',
    competency: 'Divide: a. 1- to 2-digit whole numbers resulting in a repeating (non-terminating) decimal quotient. (e. g., 1/3 = 0.3333 … ) b. a whole number by a decimal of 1 decimal place.',
    performance_standard: 'Use decimals, fractions, and ratios to solve multi-step financial and quantitative problems.',
  },
  {
    ref: '6NA-Ie-2',
    domain: 'Number and Algebra',
    content_standard: 'Operations with decimals and fractions, and ratios.',
    competency: 'Mentally divide: a. decimals of up to 4 decimal places by 0.1, 0.01, and 0.001 b. decimals of up to 2 decimal places by 10, 100, and 1000.',
    performance_standard: 'Use decimals, fractions, and ratios to solve multi-step financial and quantitative problems.',
  },
  {
    ref: '6NA-If-1',
    domain: 'Number and Algebra',
    content_standard: 'Operations with decimals and fractions, and ratios.',
    competency: 'Solve problems involving division of decimals that may or may not involve the other operations with decimals and/or whole numbers.',
    performance_standard: 'Use decimals, fractions, and ratios to solve multi-step financial and quantitative problems.',
  },
  {
    ref: '6NA-If-2',
    domain: 'Number and Algebra',
    content_standard: 'Operations with decimals and fractions, and ratios.',
    competency: 'Obtain products that result from multiplying different combinations of fractions, whole numbers, and mixed numbers.',
    performance_standard: 'Use decimals, fractions, and ratios to solve multi-step financial and quantitative problems.',
  },
  {
    ref: '6NA-If-3',
    domain: 'Number and Algebra',
    content_standard: 'Operations with decimals and fractions, and ratios.',
    competency: 'Solve multi-step problems involving multiplication that may or may not involve addition or subtraction of different combinations of fractions, whole numbers, and mixed numbers.',
    performance_standard: 'Use decimals, fractions, and ratios to solve multi-step financial and quantitative problems.',
  },
  {
    ref: '6NA-Ih-1',
    domain: 'Number and Algebra',
    content_standard: 'Operations with decimals and fractions, and ratios.',
    competency: 'Divide different combinations of fractions, whole numbers, and mixed numbers.',
    performance_standard: 'Use decimals, fractions, and ratios to solve multi-step financial and quantitative problems.',
  },
  {
    ref: '6NA-Ih-2',
    domain: 'Number and Algebra',
    content_standard: 'Operations with decimals and fractions, and ratios.',
    competency: 'Solve multi-step problems involving division of different combinations of fractions, whole numbers, and mixed numbers that may or may not involve any of the other operations of fractions.',
    performance_standard: 'Use decimals, fractions, and ratios to solve multi-step financial and quantitative problems.',
  },
  {
    ref: '6NA-Ii-1',
    domain: 'Number and Algebra',
    content_standard: 'Operations with decimals and fractions, and ratios.',
    competency: 'Describe the relationship between quantities using ratio for: a. part-whole relationships b. part-part relationships.".',
    performance_standard: 'Use decimals, fractions, and ratios to solve multi-step financial and quantitative problems.',
  },
  {
    ref: '6NA-Ii-2',
    domain: 'Number and Algebra',
    content_standard: 'Operations with decimals and fractions, and ratios.',
    competency: 'Express one number as a fraction of another given their ratio, and vice versa.',
    performance_standard: 'Use decimals, fractions, and ratios to solve multi-step financial and quantitative problems.',
  },
  {
    ref: '6NA-Ii-3',
    domain: 'Number and Algebra',
    content_standard: 'Operations with decimals and fractions, and ratios.',
    competency: 'Identify and write equivalent ratios.',
    performance_standard: 'Use decimals, fractions, and ratios to solve multi-step financial and quantitative problems.',
  },
  {
    ref: '6NA-Ii-4',
    domain: 'Number and Algebra',
    content_standard: 'Operations with decimals and fractions, and ratios.',
    competency: 'Solve problems involving ratio.',
    performance_standard: 'Use decimals, fractions, and ratios to solve multi-step financial and quantitative problems.',
  },
  {
    ref: '6NA-IIa-1',
    domain: 'Number and Algebra',
    content_standard: 'Ratio and proportion, percentages, exponential notation, and order of operations.',
    competency: 'Illustrate ratio and proportion in given situations using tables and/or the double number line model.',
    performance_standard: 'Apply ratios, percentages, exponents, and operation rules to solve practical comparison and scaling problems.',
  },
  {
    ref: '6NA-IIa-2',
    domain: 'Number and Algebra',
    content_standard: 'Ratio and proportion, percentages, exponential notation, and order of operations.',
    competency: 'Find how many times one value is larger than another given their ratio, and vice versa.',
    performance_standard: 'Apply ratios, percentages, exponents, and operation rules to solve practical comparison and scaling problems.',
  },
  {
    ref: '6NA-IIb-1',
    domain: 'Number and Algebra',
    content_standard: 'Ratio and proportion, percentages, exponential notation, and order of operations.',
    competency: 'Solve problems involving ratio and proportion.',
    performance_standard: 'Apply ratios, percentages, exponents, and operation rules to solve practical comparison and scaling problems.',
  },
  {
    ref: '6NA-IIc-1',
    domain: 'Number and Algebra',
    content_standard: 'Ratio and proportion, percentages, exponential notation, and order of operations.',
    competency: 'Illustrate and explain the relationships between percentages, fractions, and decimals.',
    performance_standard: 'Apply ratios, percentages, exponents, and operation rules to solve practical comparison and scaling problems.',
  },
  {
    ref: '6NA-IIc-2',
    domain: 'Number and Algebra',
    content_standard: 'Ratio and proportion, percentages, exponential notation, and order of operations.',
    competency: 'Identify and explain the uses of percentages.',
    performance_standard: 'Apply ratios, percentages, exponents, and operation rules to solve practical comparison and scaling problems.',
  },
  {
    ref: '6NA-IId-1',
    domain: 'Number and Algebra',
    content_standard: 'Ratio and proportion, percentages, exponential notation, and order of operations.',
    competency: 'Write numbers in exponential form e.g., 2 x 2 x 2 = 2 3 and vice versa, e.g. 2 3 = 2 x 2 x 2.',
    performance_standard: 'Apply ratios, percentages, exponents, and operation rules to solve practical comparison and scaling problems.',
  },
  {
    ref: '6NA-IId-2',
    domain: 'Number and Algebra',
    content_standard: 'Ratio and proportion, percentages, exponential notation, and order of operations.',
    competency: 'Give the value of numbers expressed in exponential form.',
    performance_standard: 'Apply ratios, percentages, exponents, and operation rules to solve practical comparison and scaling problems.',
  },
  {
    ref: '6NA-IIe-1',
    domain: 'Number and Algebra',
    content_standard: 'Ratio and proportion, percentages, exponential notation, and order of operations.',
    competency: 'Perform calculations involving numbers in exponential form by applying the GEMDAS rules.',
    performance_standard: 'Apply ratios, percentages, exponents, and operation rules to solve practical comparison and scaling problems.',
  },
  {
    ref: '6MG-IIf-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Volume, capacity, area, perimeter, and conversion of square and cubic units.',
    competency: 'Determine appropriate units for measuring volume and capacity.',
    performance_standard: 'Select and convert units and calculate measures to solve practical space, capacity, and construction problems.',
  },
  {
    ref: '6MG-IIf-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Volume, capacity, area, perimeter, and conversion of square and cubic units.',
    competency: 'Convert cu. cm to L, and vice versa.',
    performance_standard: 'Select and convert units and calculate measures to solve practical space, capacity, and construction problems.',
  },
  {
    ref: '6MG-IIg-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Volume, capacity, area, perimeter, and conversion of square and cubic units.',
    competency: 'Find the volume of a cube and of a rectangular prism using standard units of measurement.',
    performance_standard: 'Select and convert units and calculate measures to solve practical space, capacity, and construction problems.',
  },
  {
    ref: '6MG-IIg-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Volume, capacity, area, perimeter, and conversion of square and cubic units.',
    competency: 'Solve problems involving volumes of cubes and rectangular prisms.',
    performance_standard: 'Select and convert units and calculate measures to solve practical space, capacity, and construction problems.',
  },
  {
    ref: '6MG-IIg-3',
    domain: 'Measurement and Geometry',
    content_standard: 'Volume, capacity, area, perimeter, and conversion of square and cubic units.',
    competency: 'Solve problems involving capacity.',
    performance_standard: 'Select and convert units and calculate measures to solve practical space, capacity, and construction problems.',
  },
  {
    ref: '6MG-IIi-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Volume, capacity, area, perimeter, and conversion of square and cubic units.',
    competency: 'Convert sq. cm to sq. m, and vice versa.',
    performance_standard: 'Select and convert units and calculate measures to solve practical space, capacity, and construction problems.',
  },
  {
    ref: '6MG-IIi-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Volume, capacity, area, perimeter, and conversion of square and cubic units.',
    competency: 'Find the area, in sq. m or sq. cm, of composite figures composed of triangles, squares, and rectangles.',
    performance_standard: 'Select and convert units and calculate measures to solve practical space, capacity, and construction problems.',
  },
  {
    ref: '6MG-IIj-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Volume, capacity, area, perimeter, and conversion of square and cubic units.',
    competency: 'Solve problems involving the perimeter and area of triangles, parallelograms, trapezoids, and composite figures composed of triangles, squares, and rectangles.',
    performance_standard: 'Select and convert units and calculate measures to solve practical space, capacity, and construction problems.',
  },
  {
    ref: '6MG-IIIa-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Circles, circumference, area, and composite figures.',
    competency: 'Draw circles with different radii using a pair of compasses.',
    performance_standard: 'Measure and calculate circle and composite-figure dimensions in practical design and space problems.',
  },
  {
    ref: '6MG-IIIa-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Circles, circumference, area, and composite figures.',
    competency: 'Identify and describes the parts of a circle.',
    performance_standard: 'Measure and calculate circle and composite-figure dimensions in practical design and space problems.',
  },
  {
    ref: '6MG-IIIb-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Circles, circumference, area, and composite figures.',
    competency: 'Measure the circumference of circles using appropriate tools.',
    performance_standard: 'Measure and calculate circle and composite-figure dimensions in practical design and space problems.',
  },
  {
    ref: '6MG-IIIb-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Circles, circumference, area, and composite figures.',
    competency: 'Approximate the value of pi ( 𝜋 ) (the ratio of the circumference to the diameter).',
    performance_standard: 'Measure and calculate circle and composite-figure dimensions in practical design and space problems.',
  },
  {
    ref: '6MG-IIIc-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Circles, circumference, area, and composite figures.',
    competency: 'Find the circumference of a circle using C = 𝜋 d or C = 2 𝜋 r.',
    performance_standard: 'Measure and calculate circle and composite-figure dimensions in practical design and space problems.',
  },
  {
    ref: '6MG-IIIc-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Circles, circumference, area, and composite figures.',
    competency: 'Explore inductively the area of a circle leading to the formula A= 𝜋 r 2.',
    performance_standard: 'Measure and calculate circle and composite-figure dimensions in practical design and space problems.',
  },
  {
    ref: '6MG-IIId-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Circles, circumference, area, and composite figures.',
    competency: 'Find the area of a circle using the formula.',
    performance_standard: 'Measure and calculate circle and composite-figure dimensions in practical design and space problems.',
  },
  {
    ref: '6MG-IIId-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Circles, circumference, area, and composite figures.',
    competency: 'Find the area of composite figures composed of any two or more of the following: triangle, square, rectangle, circle, and semicircle.',
    performance_standard: 'Measure and calculate circle and composite-figure dimensions in practical design and space problems.',
  },
  {
    ref: '6MG-IIId-3',
    domain: 'Measurement and Geometry',
    content_standard: 'Circles, circumference, area, and composite figures.',
    competency: 'Solve problems involving circumference and area of circles, and composite figures.',
    performance_standard: 'Measure and calculate circle and composite-figure dimensions in practical design and space problems.',
  },
  {
    ref: '6SP-IIIf-1',
    domain: 'Statistics and Probability',
    content_standard: 'Construction and interpretation of pie graphs and digital data displays.',
    competency: 'Find the angle measures and/or percentages based on the given data for a pie graph.',
    performance_standard: 'Represent, interpret, and draw conclusions from proportional data in everyday and digital contexts.',
  },
  {
    ref: '6SP-IIIf-2',
    domain: 'Statistics and Probability',
    content_standard: 'Construction and interpretation of pie graphs and digital data displays.',
    competency: 'Construct a pie graph using appropriate tools.',
    performance_standard: 'Represent, interpret, and draw conclusions from proportional data in everyday and digital contexts.',
  },
  {
    ref: '6SP-IIIg-1',
    domain: 'Statistics and Probability',
    content_standard: 'Construction and interpretation of pie graphs and digital data displays.',
    competency: 'Interpret data presented in a pie graph.',
    performance_standard: 'Represent, interpret, and draw conclusions from proportional data in everyday and digital contexts.',
  },
  {
    ref: '6SP-IIIg-2',
    domain: 'Statistics and Probability',
    content_standard: 'Construction and interpretation of pie graphs and digital data displays.',
    competency: 'Interpret data from digital media that are presented in tabular or graphical form.',
    performance_standard: 'Represent, interpret, and draw conclusions from proportional data in everyday and digital contexts.',
  },
  {
    ref: '6SP-IIIh-1',
    domain: 'Statistics and Probability',
    content_standard: 'Construction and interpretation of pie graphs and digital data displays.',
    competency: 'Draw conclusions or make inferences based on data presented in a pie graph.',
    performance_standard: 'Represent, interpret, and draw conclusions from proportional data in everyday and digital contexts.',
  },
  {
    ref: '6SP-IIIh-2',
    domain: 'Statistics and Probability',
    content_standard: 'Construction and interpretation of pie graphs and digital data displays.',
    competency: 'Solve problems using data presented in a pie graph.',
    performance_standard: 'Represent, interpret, and draw conclusions from proportional data in everyday and digital contexts.',
  },
  {
    ref: '6NA-IIIi-1',
    domain: 'Number and Algebra',
    content_standard: 'Common factors, greatest common factor, common multiples, and least common multiple.',
    competency: 'Determine the common factors and the greatest common factor (GCF) of two numbers using the following methods: listing, prime factorization, and continuous division.',
    performance_standard: 'Use factors and multiples to solve practical grouping, scheduling, and sharing problems.',
  },
  {
    ref: '6NA-IIIi-2',
    domain: 'Number and Algebra',
    content_standard: 'Common factors, greatest common factor, common multiples, and least common multiple.',
    competency: 'Find the common multiples and least common multiple (LCM) of two numbers using the following methods: listing, prime factorization, and continuous division.',
    performance_standard: 'Use factors and multiples to solve practical grouping, scheduling, and sharing problems.',
  },
  {
    ref: '6NA-IIIi-3',
    domain: 'Number and Algebra',
    content_standard: 'Common factors, greatest common factor, common multiples, and least common multiple.',
    competency: 'Solve problems involving GCF and LCM.',
    performance_standard: 'Use factors and multiples to solve practical grouping, scheduling, and sharing problems.',
  },
]
