export default [
  {
    ref: '3MG-Ia-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Area of squares and rectangles, and points, lines, line segments, rays, and line relationships.',
    competency: 'Illustrate and estimate the area of a square or rectangle using square tile units.',
    performance_standard: 'Use geometric representations and area measurement to describe and solve practical spatial problems.',
  },
  {
    ref: '3MG-Ia-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Area of squares and rectangles, and points, lines, line segments, rays, and line relationships.',
    competency: 'Explore inductively the derivation of the formulas for the areas of a square and a rectangle using square tile units.',
    performance_standard: 'Use geometric representations and area measurement to describe and solve practical spatial problems.',
  },
  {
    ref: '3MG-Ib-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Area of squares and rectangles, and points, lines, line segments, rays, and line relationships.',
    competency: 'Find the areas of squares and rectangles in sq. cm and sq. m.',
    performance_standard: 'Use geometric representations and area measurement to describe and solve practical spatial problems.',
  },
  {
    ref: '3MG-Ib-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Area of squares and rectangles, and points, lines, line segments, rays, and line relationships.',
    competency: 'Solve problems involving areas of squares and rectangles.',
    performance_standard: 'Use geometric representations and area measurement to describe and solve practical spatial problems.',
  },
  {
    ref: '3MG-Ib-3',
    domain: 'Measurement and Geometry',
    content_standard: 'Area of squares and rectangles, and points, lines, line segments, rays, and line relationships.',
    competency: 'Recognize, using models, and draw a point, line, line segment, and ray.',
    performance_standard: 'Use geometric representations and area measurement to describe and solve practical spatial problems.',
  },
  {
    ref: '3MG-Ic-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Area of squares and rectangles, and points, lines, line segments, rays, and line relationships.',
    competency: 'Recognize and draw parallel, intersecting, and perpendicular lines.',
    performance_standard: 'Use geometric representations and area measurement to describe and solve practical spatial problems.',
  },
  {
    ref: '3MG-Ic-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Area of squares and rectangles, and points, lines, line segments, rays, and line relationships.',
    competency: 'Identify and draw line segments of equal length using a ruler.',
    performance_standard: 'Use geometric representations and area measurement to describe and solve practical spatial problems.',
  },
  {
    ref: '3NA-Id-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 10 000, ordinal numbers up to 100th, place value, comparison, ordering, and rounding.',
    competency: 'Represent numbers up to 10 000 using pictorial models and numerals.',
    performance_standard: 'Use whole numbers up to 10 000 to describe, compare, estimate, and organize quantities in daily life.',
  },
  {
    ref: '3NA-Ie-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 10 000, ordinal numbers up to 100th, place value, comparison, ordering, and rounding.',
    competency: 'Read and write numbers up to 10 000 in numerals and in words.',
    performance_standard: 'Use whole numbers up to 10 000 to describe, compare, estimate, and organize quantities in daily life.',
  },
  {
    ref: '3NA-If-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 10 000, ordinal numbers up to 100th, place value, comparison, ordering, and rounding.',
    competency: 'Describe the position of objects using ordinal numbers up to 100th.',
    performance_standard: 'Use whole numbers up to 10 000 to describe, compare, estimate, and organize quantities in daily life.',
  },
  {
    ref: '3NA-Ig-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 10 000, ordinal numbers up to 100th, place value, comparison, ordering, and rounding.',
    competency: 'Determine: a. the place value of a digit in a 4-digit number b. the value of a digit c. the digit of number, given its place value.',
    performance_standard: 'Use whole numbers up to 10 000 to describe, compare, estimate, and organize quantities in daily life.',
  },
  {
    ref: '3NA-Ii-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 10 000, ordinal numbers up to 100th, place value, comparison, ordering, and rounding.',
    competency: 'Round numbers to the nearest ten, hundred, or thousand.',
    performance_standard: 'Use whole numbers up to 10 000 to describe, compare, estimate, and organize quantities in daily life.',
  },
  {
    ref: '3NA-Ii-2',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 10 000, ordinal numbers up to 100th, place value, comparison, ordering, and rounding.',
    competency: 'Compare numbers up to 10 000 using the symbols =, >, and <.',
    performance_standard: 'Use whole numbers up to 10 000 to describe, compare, estimate, and organize quantities in daily life.',
  },
  {
    ref: '3NA-Ij-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 10 000, ordinal numbers up to 100th, place value, comparison, ordering, and rounding.',
    competency: 'Order numbers up to 10 000 from smallest to largest, and vice versa.',
    performance_standard: 'Use whole numbers up to 10 000 to describe, compare, estimate, and organize quantities in daily life.',
  },
  {
    ref: '3MG-IIa-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Measurement, estimation, and comparison of mass and capacity using metric units.',
    competency: 'Measure mass in grams (g), kilograms (kg) and/or milligrams (mg), using appropriate measuring tools.',
    performance_standard: 'Select tools and metric units to measure and compare mass and capacity in practical situations.',
  },
  {
    ref: '3MG-IIa-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Measurement, estimation, and comparison of mass and capacity using metric units.',
    competency: 'Estimate mass of an object using grams, kilograms, and/or milligrams.',
    performance_standard: 'Select tools and metric units to measure and compare mass and capacity in practical situations.',
  },
  {
    ref: '3MG-IIa-3',
    domain: 'Measurement and Geometry',
    content_standard: 'Measurement, estimation, and comparison of mass and capacity using metric units.',
    competency: 'Compare masses of objects including the use of a balance scale.',
    performance_standard: 'Select tools and metric units to measure and compare mass and capacity in practical situations.',
  },
  {
    ref: '3MG-IIb-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Measurement, estimation, and comparison of mass and capacity using metric units.',
    competency: 'Measure capacity in liters (L) and/or milliliters (mL), using appropriate measuring tools.',
    performance_standard: 'Select tools and metric units to measure and compare mass and capacity in practical situations.',
  },
  {
    ref: '3MG-IIb-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Measurement, estimation, and comparison of mass and capacity using metric units.',
    competency: 'Estimate capacity using liters and/or milliliters.',
    performance_standard: 'Select tools and metric units to measure and compare mass and capacity in practical situations.',
  },
  {
    ref: '3MG-IIb-3',
    domain: 'Measurement and Geometry',
    content_standard: 'Measurement, estimation, and comparison of mass and capacity using metric units.',
    competency: 'Compare capacities of two containers.',
    performance_standard: 'Select tools and metric units to measure and compare mass and capacity in practical situations.',
  },
  {
    ref: '3NA-IIc-1',
    domain: 'Number and Algebra',
    content_standard: 'Philippine money and addition and subtraction involving numbers up to 10 000.',
    competency: 'Read and write money in words and using: a. Philippine currency symbols (₱ and PhP) up to ₱10 000 b. the centavo sign.',
    performance_standard: 'Use addition, subtraction, estimation, and money notation to solve everyday financial and quantitative problems.',
  },
  {
    ref: '3NA-IIc-2',
    domain: 'Number and Algebra',
    content_standard: 'Philippine money and addition and subtraction involving numbers up to 10 000.',
    competency: 'Add numbers with sums up to 10 000, with and without regrouping.',
    performance_standard: 'Use addition, subtraction, estimation, and money notation to solve everyday financial and quantitative problems.',
  },
  {
    ref: '3NA-IId-1',
    domain: 'Number and Algebra',
    content_standard: 'Philippine money and addition and subtraction involving numbers up to 10 000.',
    competency: 'Estimate the sum of addends with up to 4 digits.',
    performance_standard: 'Use addition, subtraction, estimation, and money notation to solve everyday financial and quantitative problems.',
  },
  {
    ref: '3NA-IId-2',
    domain: 'Number and Algebra',
    content_standard: 'Philippine money and addition and subtraction involving numbers up to 10 000.',
    competency: 'Solve problems involving addition of numbers with sums up to 10 000, including problems involving money.',
    performance_standard: 'Use addition, subtraction, estimation, and money notation to solve everyday financial and quantitative problems.',
  },
  {
    ref: '3NA-IIe-1',
    domain: 'Number and Algebra',
    content_standard: 'Philippine money and addition and subtraction involving numbers up to 10 000.',
    competency: 'Subtract numbers, where both numbers are less than 10 000, with and without regrouping.',
    performance_standard: 'Use addition, subtraction, estimation, and money notation to solve everyday financial and quantitative problems.',
  },
  {
    ref: '3NA-IIf-1',
    domain: 'Number and Algebra',
    content_standard: 'Philippine money and addition and subtraction involving numbers up to 10 000.',
    competency: 'Estimate the difference of two numbers of up to 4 digits.',
    performance_standard: 'Use addition, subtraction, estimation, and money notation to solve everyday financial and quantitative problems.',
  },
  {
    ref: '3NA-IIf-2',
    domain: 'Number and Algebra',
    content_standard: 'Philippine money and addition and subtraction involving numbers up to 10 000.',
    competency: 'Perform addition and subtraction of 3 to 4 numbers of up to 2 digits, observing correct order of operations.',
    performance_standard: 'Use addition, subtraction, estimation, and money notation to solve everyday financial and quantitative problems.',
  },
  {
    ref: '3NA-IIh-1',
    domain: 'Number and Algebra',
    content_standard: 'Philippine money and addition and subtraction involving numbers up to 10 000.',
    competency: 'Solve problems involving addition and subtraction with 3 to 4 numbers of up to 2 digits, including problems involving money.',
    performance_standard: 'Use addition, subtraction, estimation, and money notation to solve everyday financial and quantitative problems.',
  },
  {
    ref: '3SP-IIh-1',
    domain: 'Statistics and Probability',
    content_standard: 'Experimental data, tables, bar graphs, and likelihood of outcomes.',
    competency: 'Collect data from experiments with a small number of possible outcomes (e.g., rolling a die or tossing a coin).',
    performance_standard: 'Collect, represent, interpret, and compare data and likely outcomes from familiar situations.',
  },
  {
    ref: '3SP-IIi-1',
    domain: 'Statistics and Probability',
    content_standard: 'Experimental data, tables, bar graphs, and likelihood of outcomes.',
    competency: 'Present data in tables and single bar graphs (horizontal and vertical).',
    performance_standard: 'Collect, represent, interpret, and compare data and likely outcomes from familiar situations.',
  },
  {
    ref: '3SP-IIi-2',
    domain: 'Statistics and Probability',
    content_standard: 'Experimental data, tables, bar graphs, and likelihood of outcomes.',
    competency: 'Interpret data in tables and single bar graphs (horizontal and vertical).',
    performance_standard: 'Collect, represent, interpret, and compare data and likely outcomes from familiar situations.',
  },
  {
    ref: '3SP-IIj-1',
    domain: 'Statistics and Probability',
    content_standard: 'Experimental data, tables, bar graphs, and likelihood of outcomes.',
    competency: 'Solve problems using data presented in a single bar graph (horizontal and vertical).',
    performance_standard: 'Collect, represent, interpret, and compare data and likely outcomes from familiar situations.',
  },
  {
    ref: '3SP-IIj-2',
    domain: 'Statistics and Probability',
    content_standard: 'Experimental data, tables, bar graphs, and likelihood of outcomes.',
    competency: 'Describe and compare outcomes in real-life situations using the following terms: equally likely, less/least likely, more/most likely, certain, and impossible.',
    performance_standard: 'Collect, represent, interpret, and compare data and likely outcomes from familiar situations.',
  },
  {
    ref: '3NA-IIIa-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division, numerical patterns, and fractions equal to or greater than one.',
    competency: 'Multiply numbers using the 6, 7, 8, and 9 multiplication tables.',
    performance_standard: 'Apply multiplication, division, patterns, and fractions to solve practical grouping and sharing problems.',
  },
  {
    ref: '3NA-IIIb-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division, numerical patterns, and fractions equal to or greater than one.',
    competency: 'Illustrate and apply properties of multiplication for the 6, 7, 8, and 9 multiplication tables: a. one multiplied by any number is equal to the number b. zero multiplied by any number is zero c. changing the order of the numbers being multiplied does not change the product d. changing the grouping of the numbers being multiplied does not change the product e. multiplying the sum of two addends by a number is the same as the sum of the products of a number by each addend.',
    performance_standard: 'Apply multiplication, division, patterns, and fractions to solve practical grouping and sharing problems.',
  },
  {
    ref: '3NA-IIIc-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division, numerical patterns, and fractions equal to or greater than one.',
    competency: 'Multiply numbers with and without regrouping: a. 2- to 3-digit numbers by a 1-digit number b. 2- to 4-digit numbers by a number whose leading digit is the only non-zero digit, with products up to 10 000.',
    performance_standard: 'Apply multiplication, division, patterns, and fractions to solve practical grouping and sharing problems.',
  },
  {
    ref: '3NA-IIIc-2',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division, numerical patterns, and fractions equal to or greater than one.',
    competency: 'Estimate the product of 2- to 3-digit numbers by 1- to 2-digit numbers by estimating the factors using multiples of 10.',
    performance_standard: 'Apply multiplication, division, patterns, and fractions to solve practical grouping and sharing problems.',
  },
  {
    ref: '3NA-IIId-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division, numerical patterns, and fractions equal to or greater than one.',
    competency: 'Solve 1-to 2-step multiplication problems, including problems involving money.',
    performance_standard: 'Apply multiplication, division, patterns, and fractions to solve practical grouping and sharing problems.',
  },
  {
    ref: '3NA-IIId-2',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division, numerical patterns, and fractions equal to or greater than one.',
    competency: 'Determine the missing term/s in a pattern with repeating and increasing components or repeating and decreasing components (e.g., 1a, 1b, 1c, 2a, 2b, 2c, …).',
    performance_standard: 'Apply multiplication, division, patterns, and fractions to solve practical grouping and sharing problems.',
  },
  {
    ref: '3NA-IIId-3',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division, numerical patterns, and fractions equal to or greater than one.',
    competency: 'Explain how to generate a given pattern with repeating and increasing components or repeating and decreasing components.',
    performance_standard: 'Apply multiplication, division, patterns, and fractions to solve practical grouping and sharing problems.',
  },
  {
    ref: '3NA-IIIe-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division, numerical patterns, and fractions equal to or greater than one.',
    competency: 'Illustrate division through equal jumps on the number line and as inverse of multiplication.',
    performance_standard: 'Apply multiplication, division, patterns, and fractions to solve practical grouping and sharing problems.',
  },
  {
    ref: '3NA-IIIf-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division, numerical patterns, and fractions equal to or greater than one.',
    competency: 'Divide numbers using the 6, 7, 8, and 9 multiplication tables.',
    performance_standard: 'Apply multiplication, division, patterns, and fractions to solve practical grouping and sharing problems.',
  },
  {
    ref: '3NA-IIIf-2',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division, numerical patterns, and fractions equal to or greater than one.',
    competency: 'Find the missing number in a number sentence involving multiplication or division by 6, 7, 8, and 9 (e.g., x 7 = 56; 56 ÷ = 7).',
    performance_standard: 'Apply multiplication, division, patterns, and fractions to solve practical grouping and sharing problems.',
  },
  {
    ref: '3NA-IIIg-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division, numerical patterns, and fractions equal to or greater than one.',
    competency: 'Divide numbers with and without remainder: a. 2- to 3-digit numbers by 1-digit number without remainder b. 2-digit numbers by 1-digit number with remainder c. 2- to 4-digit numbers by 10,100, and 1000.',
    performance_standard: 'Apply multiplication, division, patterns, and fractions to solve practical grouping and sharing problems.',
  },
  {
    ref: '3NA-IIIh-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division, numerical patterns, and fractions equal to or greater than one.',
    competency: 'Estimate the quotient of 2- to 3-digit numbers divided by 1- to 2-digit numbers, using multiples of 10 or 100 as appropriate.',
    performance_standard: 'Apply multiplication, division, patterns, and fractions to solve practical grouping and sharing problems.',
  },
  {
    ref: '3NA-IIIh-2',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division, numerical patterns, and fractions equal to or greater than one.',
    competency: 'Solve division problems involving 2- to 3 -digit numbers by a 1-digit number, including problems involving money.',
    performance_standard: 'Apply multiplication, division, patterns, and fractions to solve practical grouping and sharing problems.',
  },
  {
    ref: '3NA-IIIh-3',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division, numerical patterns, and fractions equal to or greater than one.',
    competency: 'Represent fractions that are equal to one and greater than one using models.',
    performance_standard: 'Apply multiplication, division, patterns, and fractions to solve practical grouping and sharing problems.',
  },
  {
    ref: '3NA-IIIh-4',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division, numerical patterns, and fractions equal to or greater than one.',
    competency: 'Add and subtract similar fractions using models.',
    performance_standard: 'Apply multiplication, division, patterns, and fractions to solve practical grouping and sharing problems.',
  },
  {
    ref: '3MG-IIIi-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Two-direction translations and line symmetry.',
    competency: 'Describe and draw the effect of a two-direction multi-step slide (or translation) in basic shapes and figures.',
    performance_standard: 'Use translations and symmetry to create, complete, and describe designs and spatial arrangements.',
  },
  {
    ref: '3MG-IIIj-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Two-direction translations and line symmetry.',
    competency: 'Identify shapes or figures that show line symmetry by drawing the line of symmetry.',
    performance_standard: 'Use translations and symmetry to create, complete, and describe designs and spatial arrangements.',
  },
  {
    ref: '3MG-IIIj-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Two-direction translations and line symmetry.',
    competency: 'Complete a figure that is symmetric with respect to a line.',
    performance_standard: 'Use translations and symmetry to create, complete, and describe designs and spatial arrangements.',
  },
]
