export default [
  {
    ref: '4MG-Ia-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Angles, properties of triangles and quadrilaterals, and perimeter of composite figures.',
    competency: 'Illustrate different angles (right, acute, and obtuse) using models.',
    performance_standard: 'Measure, classify, and use geometric figures to solve practical design and boundary problems.',
  },
  {
    ref: '4MG-Ia-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Angles, properties of triangles and quadrilaterals, and perimeter of composite figures.',
    competency: 'Measure and draw angles using a protractor.',
    performance_standard: 'Measure, classify, and use geometric figures to solve practical design and boundary problems.',
  },
  {
    ref: '4MG-Ib-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Angles, properties of triangles and quadrilaterals, and perimeter of composite figures.',
    competency: 'Draw and state the properties of triangles and quadrilaterals.',
    performance_standard: 'Measure, classify, and use geometric figures to solve practical design and boundary problems.',
  },
  {
    ref: '4MG-Ic-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Angles, properties of triangles and quadrilaterals, and perimeter of composite figures.',
    competency: 'Classify triangles and quadrilaterals according to sides and angles.',
    performance_standard: 'Measure, classify, and use geometric figures to solve practical design and boundary problems.',
  },
  {
    ref: '4MG-Ic-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Angles, properties of triangles and quadrilaterals, and perimeter of composite figures.',
    competency: 'Differentiate different quadrilaterals.',
    performance_standard: 'Measure, classify, and use geometric figures to solve practical design and boundary problems.',
  },
  {
    ref: '4MG-Id-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Angles, properties of triangles and quadrilaterals, and perimeter of composite figures.',
    competency: 'Find the perimeter of quadrilaterals that are not squares or rectangles.',
    performance_standard: 'Measure, classify, and use geometric figures to solve practical design and boundary problems.',
  },
  {
    ref: '4MG-Id-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Angles, properties of triangles and quadrilaterals, and perimeter of composite figures.',
    competency: 'Find the perimeter of composite figures composed of triangles and quadrilaterals.',
    performance_standard: 'Measure, classify, and use geometric figures to solve practical design and boundary problems.',
  },
  {
    ref: '4NA-Ie-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000 000 and the four operations with whole numbers.',
    competency: 'Read and write numbers up to 1 000 000 in numerals and in words.',
    performance_standard: 'Use large whole numbers and operations to estimate and solve multi-step problems in everyday contexts.',
  },
  {
    ref: '4NA-Ie-2',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000 000 and the four operations with whole numbers.',
    competency: 'Determine: a. the place value of a digit in a 6-digit number b. the value of a digit c. the digit of number, given its place value.',
    performance_standard: 'Use large whole numbers and operations to estimate and solve multi-step problems in everyday contexts.',
  },
  {
    ref: '4NA-If-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000 000 and the four operations with whole numbers.',
    competency: 'Compare numbers up to 1 000 000 using =, < and >.',
    performance_standard: 'Use large whole numbers and operations to estimate and solve multi-step problems in everyday contexts.',
  },
  {
    ref: '4NA-If-2',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000 000 and the four operations with whole numbers.',
    competency: 'Round numbers to the nearest hundred thousand.',
    performance_standard: 'Use large whole numbers and operations to estimate and solve multi-step problems in everyday contexts.',
  },
  {
    ref: '4NA-If-3',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000 000 and the four operations with whole numbers.',
    competency: 'Estimate the sum and difference of two 5- to 6-digit numbers by rounding the addends to the nearest large place value of the numbers.',
    performance_standard: 'Use large whole numbers and operations to estimate and solve multi-step problems in everyday contexts.',
  },
  {
    ref: '4NA-Ig-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000 000 and the four operations with whole numbers.',
    competency: 'Add numbers with sums up to 1 000 000 and subtracts numbers where both numbers are less than 1 000 000, with and without regrouping.',
    performance_standard: 'Use large whole numbers and operations to estimate and solve multi-step problems in everyday contexts.',
  },
  {
    ref: '4NA-Ig-2',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000 000 and the four operations with whole numbers.',
    competency: 'Multiply two numbers with and without regrouping: a. 3- to 4-digit numbers by a 1-digit number b. 2- to 3-digit numbers by 2-digit numbers, with products up to 1 000 000.".',
    performance_standard: 'Use large whole numbers and operations to estimate and solve multi-step problems in everyday contexts.',
  },
  {
    ref: '4NA-Ig-3',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000 000 and the four operations with whole numbers.',
    competency: 'Estimate the result of multiplying two numbers where the product is less than 1 000 000.',
    performance_standard: 'Use large whole numbers and operations to estimate and solve multi-step problems in everyday contexts.',
  },
  {
    ref: '4NA-Ii-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000 000 and the four operations with whole numbers.',
    competency: 'Solve multi-step problems involving one or more of the four operations with results of calculations up to 1 000 000, including problems involving money.',
    performance_standard: 'Use large whole numbers and operations to estimate and solve multi-step problems in everyday contexts.',
  },
  {
    ref: '4NA-Ii-2',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000 000 and the four operations with whole numbers.',
    competency: 'Divide two numbers with and without regrouping: a. 3- to 4-digit numbers by 1-digit numbers b. 2- to 3-digit numbers by 2-digit numbers".',
    performance_standard: 'Use large whole numbers and operations to estimate and solve multi-step problems in everyday contexts.',
  },
  {
    ref: '4NA-Ii-3',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 1 000 000 and the four operations with whole numbers.',
    competency: 'Estimate the quotient when dividing 3- to 4-digit dividends by 1- to 2-digit divisors, by first estimating the dividends and divisors using multiples of 10.',
    performance_standard: 'Use large whole numbers and operations to estimate and solve multi-step problems in everyday contexts.',
  },
  {
    ref: '4NA-IIa-1',
    domain: 'Number and Algebra',
    content_standard: 'Number sentences, MDAS, fractions, factors, and multiples.',
    competency: 'Represent situations involving one or more of the four operations using a number sentence.',
    performance_standard: 'Use operation rules and fraction relationships to represent and solve practical quantitative situations.',
  },
  {
    ref: '4NA-IIa-2',
    domain: 'Number and Algebra',
    content_standard: 'Number sentences, MDAS, fractions, factors, and multiples.',
    competency: 'Perform two or more different operations by applying the MDAS rules.',
    performance_standard: 'Use operation rules and fraction relationships to represent and solve practical quantitative situations.',
  },
  {
    ref: '4MG-IIc-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Conversion of units of length, mass, capacity, and time.',
    competency: 'Convert common units of measure from larger to smaller units, and vice versa: a. meter and centimeter b. kilometer and meter c. kilogram and gram d. gram and milligram e. liter and milliliter.',
    performance_standard: 'Convert measurement units and solve everyday problems involving length, mass, capacity, and elapsed time.',
  },
  {
    ref: '4MG-IIc-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Conversion of units of length, mass, capacity, and time.',
    competency: 'Convert time measures from smaller to larger units, and vice versa: a. seconds to minutes b. minutes to hours c. hours to days d. days to weeks e. weeks to months f. months to years.',
    performance_standard: 'Convert measurement units and solve everyday problems involving length, mass, capacity, and elapsed time.',
  },
  {
    ref: '4MG-IId-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Conversion of units of length, mass, capacity, and time.',
    competency: 'Solve problems involving conversion of units of length, mass, capacity, and time, including problems involving elapsed time in hours and minutes.',
    performance_standard: 'Convert measurement units and solve everyday problems involving length, mass, capacity, and elapsed time.',
  },
  {
    ref: '4NA-IIe-1',
    domain: 'Number and Algebra',
    content_standard: 'Number sentences, MDAS, fractions, factors, and multiples.',
    competency: 'Identify proper fractions, improper fractions, and mixed numbers.',
    performance_standard: 'Use operation rules and fraction relationships to represent and solve practical quantitative situations.',
  },
  {
    ref: '4NA-IIe-2',
    domain: 'Number and Algebra',
    content_standard: 'Number sentences, MDAS, fractions, factors, and multiples.',
    competency: 'Rewrite improper fractions into mixed numbers, and vice versa.',
    performance_standard: 'Use operation rules and fraction relationships to represent and solve practical quantitative situations.',
  },
  {
    ref: '4NA-IIe-3',
    domain: 'Number and Algebra',
    content_standard: 'Number sentences, MDAS, fractions, factors, and multiples.',
    competency: 'Plot fraction (proper fractions, improper fractions, and mixed numbers) with denominators 2, 4, 5, and 10 on the number line.',
    performance_standard: 'Use operation rules and fraction relationships to represent and solve practical quantitative situations.',
  },
  {
    ref: '4NA-IIf-1',
    domain: 'Number and Algebra',
    content_standard: 'Number sentences, MDAS, fractions, factors, and multiples.',
    competency: 'Add and subtract similar fractions: a. two proper fractions b. two mixed numbers c. a mixed number and a proper fraction d. a whole number and a proper fraction e. a whole number and a mixed number.',
    performance_standard: 'Use operation rules and fraction relationships to represent and solve practical quantitative situations.',
  },
  {
    ref: '4NA-IIg-1',
    domain: 'Number and Algebra',
    content_standard: 'Number sentences, MDAS, fractions, factors, and multiples.',
    competency: 'Represent dissimilar fractions, with denominators up to 10, using models.',
    performance_standard: 'Use operation rules and fraction relationships to represent and solve practical quantitative situations.',
  },
  {
    ref: '4NA-IIg-2',
    domain: 'Number and Algebra',
    content_standard: 'Number sentences, MDAS, fractions, factors, and multiples.',
    competency: 'Compare dissimilar fractions using the symbols =, >, and <.',
    performance_standard: 'Use operation rules and fraction relationships to represent and solve practical quantitative situations.',
  },
  {
    ref: '4NA-IIh-1',
    domain: 'Number and Algebra',
    content_standard: 'Number sentences, MDAS, fractions, factors, and multiples.',
    competency: 'Order dissimilar fractions from smallest to largest, and vice versa.',
    performance_standard: 'Use operation rules and fraction relationships to represent and solve practical quantitative situations.',
  },
  {
    ref: '4NA-IIh-2',
    domain: 'Number and Algebra',
    content_standard: 'Number sentences, MDAS, fractions, factors, and multiples.',
    competency: 'Generate equivalent fractions using models.',
    performance_standard: 'Use operation rules and fraction relationships to represent and solve practical quantitative situations.',
  },
  {
    ref: '4NA-IIi-1',
    domain: 'Number and Algebra',
    content_standard: 'Number sentences, MDAS, fractions, factors, and multiples.',
    competency: 'Determine equivalent fractions.',
    performance_standard: 'Use operation rules and fraction relationships to represent and solve practical quantitative situations.',
  },
  {
    ref: '4NA-IIi-2',
    domain: 'Number and Algebra',
    content_standard: 'Number sentences, MDAS, fractions, factors, and multiples.',
    competency: 'Identify the multiples of given numbers up to 100.',
    performance_standard: 'Use operation rules and fraction relationships to represent and solve practical quantitative situations.',
  },
  {
    ref: '4NA-IIi-3',
    domain: 'Number and Algebra',
    content_standard: 'Number sentences, MDAS, fractions, factors, and multiples.',
    competency: 'Find all the factors of a given number up to 100.',
    performance_standard: 'Use operation rules and fraction relationships to represent and solve practical quantitative situations.',
  },
  {
    ref: '4NA-IIi-4',
    domain: 'Number and Algebra',
    content_standard: 'Number sentences, MDAS, fractions, factors, and multiples.',
    competency: 'Reduce fractions to simplest form.',
    performance_standard: 'Use operation rules and fraction relationships to represent and solve practical quantitative situations.',
  },
  {
    ref: '4NA-IIIa-1',
    domain: 'Number and Algebra',
    content_standard: 'Operations with dissimilar fractions, patterns, number sentences, and decimal numbers to hundredths.',
    competency: 'Add and subtract dissimilar fractions using models.',
    performance_standard: 'Use fractions, decimals, patterns, and number properties to solve practical problems and explain relationships.',
  },
  {
    ref: '4NA-IIIb-1',
    domain: 'Number and Algebra',
    content_standard: 'Operations with dissimilar fractions, patterns, number sentences, and decimal numbers to hundredths.',
    competency: 'Add and subtract dissimilar fractions: a. two proper fractions b. two mixed numbers c. a mixed number and a proper fraction d. a whole number and a proper fraction e. a whole number and a mixed number.',
    performance_standard: 'Use fractions, decimals, patterns, and number properties to solve practical problems and explain relationships.',
  },
  {
    ref: '4NA-IIIc-1',
    domain: 'Number and Algebra',
    content_standard: 'Operations with dissimilar fractions, patterns, number sentences, and decimal numbers to hundredths.',
    competency: 'Solve multi-step problems involving addition and/or subtraction of fractions.',
    performance_standard: 'Use fractions, decimals, patterns, and number properties to solve practical problems and explain relationships.',
  },
  {
    ref: '4MG-IIId-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Line symmetry, reflection, and glide reflection.',
    competency: 'Identify symmetry with respect to a line.',
    performance_standard: 'Apply symmetry and reflection to complete and transform figures in designs and spatial tasks.',
  },
  {
    ref: '4MG-IIId-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Line symmetry, reflection, and glide reflection.',
    competency: 'Complete a figure that is symmetric with respect to a line.',
    performance_standard: 'Apply symmetry and reflection to complete and transform figures in designs and spatial tasks.',
  },
  {
    ref: '4MG-IIId-3',
    domain: 'Measurement and Geometry',
    content_standard: 'Line symmetry, reflection, and glide reflection.',
    competency: 'Draws the image of an object after applying reflection with respect to a line, including glide reflection.',
    performance_standard: 'Apply symmetry and reflection to complete and transform figures in designs and spatial tasks.',
  },
  {
    ref: '4SP-IIIe-1',
    domain: 'Statistics and Probability',
    content_standard: 'Collection, presentation, and interpretation of time-based data in tables and single line graphs.',
    competency: 'Collect data with time element using appropriate sources.',
    performance_standard: 'Use tables and line graphs to analyze changes over time and solve real-life data problems.',
  },
  {
    ref: '4SP-IIIe-2',
    domain: 'Statistics and Probability',
    content_standard: 'Collection, presentation, and interpretation of time-based data in tables and single line graphs.',
    competency: 'Present data in a tabular form, or in a single line graph.',
    performance_standard: 'Use tables and line graphs to analyze changes over time and solve real-life data problems.',
  },
  {
    ref: '4SP-IIIf-1',
    domain: 'Statistics and Probability',
    content_standard: 'Collection, presentation, and interpretation of time-based data in tables and single line graphs.',
    competency: 'Interpret data presented in a tabular form, or in a single line graph.',
    performance_standard: 'Use tables and line graphs to analyze changes over time and solve real-life data problems.',
  },
  {
    ref: '4SP-IIIf-2',
    domain: 'Statistics and Probability',
    content_standard: 'Collection, presentation, and interpretation of time-based data in tables and single line graphs.',
    competency: 'Solve problems using data for at most two variables in a tabular form, or in a single line graph.',
    performance_standard: 'Use tables and line graphs to analyze changes over time and solve real-life data problems.',
  },
  {
    ref: '4NA-IIIg-1',
    domain: 'Number and Algebra',
    content_standard: 'Operations with dissimilar fractions, patterns, number sentences, and decimal numbers to hundredths.',
    competency: 'Describe the rule used to generate a given simple pattern.',
    performance_standard: 'Use fractions, decimals, patterns, and number properties to solve practical problems and explain relationships.',
  },
  {
    ref: '4NA-IIIg-2',
    domain: 'Number and Algebra',
    content_standard: 'Operations with dissimilar fractions, patterns, number sentences, and decimal numbers to hundredths.',
    competency: 'Complete a number sentence: a. to represent a property of operations (e.g., 4 + 3 = 3 + ) (commutative property of addition) b. to represent equivalent number facts (e.g., 4 + = 6 + 3).',
    performance_standard: 'Use fractions, decimals, patterns, and number properties to solve practical problems and explain relationships.',
  },
  {
    ref: '4NA-IIIg-3',
    domain: 'Number and Algebra',
    content_standard: 'Operations with dissimilar fractions, patterns, number sentences, and decimal numbers to hundredths.',
    competency: 'Represent decimal numbers using models and manipulatives to show the relationship to fractions.',
    performance_standard: 'Use fractions, decimals, patterns, and number properties to solve practical problems and explain relationships.',
  },
  {
    ref: '4NA-IIIg-4',
    domain: 'Number and Algebra',
    content_standard: 'Operations with dissimilar fractions, patterns, number sentences, and decimal numbers to hundredths.',
    competency: 'Read and write decimal numbers with decimal parts to hundredths.',
    performance_standard: 'Use fractions, decimals, patterns, and number properties to solve practical problems and explain relationships.',
  },
  {
    ref: '4NA-IIIi-1',
    domain: 'Number and Algebra',
    content_standard: 'Operations with dissimilar fractions, patterns, number sentences, and decimal numbers to hundredths.',
    competency: 'Determine: a. the place value to hundredths of a digit in a given decimal number b. the value of a digit c. the digit of number, given its place value.',
    performance_standard: 'Use fractions, decimals, patterns, and number properties to solve practical problems and explain relationships.',
  },
  {
    ref: '4NA-IIIi-2',
    domain: 'Number and Algebra',
    content_standard: 'Operations with dissimilar fractions, patterns, number sentences, and decimal numbers to hundredths.',
    competency: 'Convert decimal numbers to fractions, and fractions with denominators 10 or 100 to decimals.',
    performance_standard: 'Use fractions, decimals, patterns, and number properties to solve practical problems and explain relationships.',
  },
  {
    ref: '4NA-IIIi-3',
    domain: 'Number and Algebra',
    content_standard: 'Operations with dissimilar fractions, patterns, number sentences, and decimal numbers to hundredths.',
    competency: 'Plot decimal numbers with tenth decimal part on the number line.',
    performance_standard: 'Use fractions, decimals, patterns, and number properties to solve practical problems and explain relationships.',
  },
  {
    ref: '4NA-IIIi-4',
    domain: 'Number and Algebra',
    content_standard: 'Operations with dissimilar fractions, patterns, number sentences, and decimal numbers to hundredths.',
    competency: 'Compare and order decimal numbers with decimal parts to hundredths.',
    performance_standard: 'Use fractions, decimals, patterns, and number properties to solve practical problems and explain relationships.',
  },
  {
    ref: '4NA-IIIi-5',
    domain: 'Number and Algebra',
    content_standard: 'Operations with dissimilar fractions, patterns, number sentences, and decimal numbers to hundredths.',
    competency: 'Round decimal numbers to the nearest whole number and to the nearest tenth.',
    performance_standard: 'Use fractions, decimals, patterns, and number properties to solve practical problems and explain relationships.',
  },
]
