export default [
  {
    ref: '5MG-Ia-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Twelve- and twenty-four-hour time, world time zones, and areas of parallelograms, triangles, and trapezoids.',
    competency: 'Describe a 12- and 24-hour clock system.',
    performance_standard: 'Use time systems, time zones, and area formulas to solve scheduling and measurement problems.',
  },
  {
    ref: '5MG-Ia-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Twelve- and twenty-four-hour time, world time zones, and areas of parallelograms, triangles, and trapezoids.',
    competency: 'Convert 12-hour time to 24-hour time, and vice-versa.',
    performance_standard: 'Use time systems, time zones, and area formulas to solve scheduling and measurement problems.',
  },
  {
    ref: '5MG-Ia-3',
    domain: 'Measurement and Geometry',
    content_standard: 'Twelve- and twenty-four-hour time, world time zones, and areas of parallelograms, triangles, and trapezoids.',
    competency: 'Solve problems involving 12- and 24-hour time.',
    performance_standard: 'Use time systems, time zones, and area formulas to solve scheduling and measurement problems.',
  },
  {
    ref: '5MG-Ib-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Twelve- and twenty-four-hour time, world time zones, and areas of parallelograms, triangles, and trapezoids.',
    competency: 'Compare the time in different world time zones to the time in the Philippines using a world time zone map.',
    performance_standard: 'Use time systems, time zones, and area formulas to solve scheduling and measurement problems.',
  },
  {
    ref: '5MG-Ib-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Twelve- and twenty-four-hour time, world time zones, and areas of parallelograms, triangles, and trapezoids.',
    competency: 'Solve problems on comparing the time in different world time zones to the time in the Philippines.',
    performance_standard: 'Use time systems, time zones, and area formulas to solve scheduling and measurement problems.',
  },
  {
    ref: '5NA-Ic-1',
    domain: 'Number and Algebra',
    content_standard: 'GMDAS, multiplication and division of fractions, and decimal numbers to thousandths.',
    competency: 'Perform three or more different operations by applying the GMDAS rules.',
    performance_standard: 'Apply operation rules, fractions, and decimals to solve multi-step real-life problems.',
  },
  {
    ref: '5NA-Ic-2',
    domain: 'Number and Algebra',
    content_standard: 'GMDAS, multiplication and division of fractions, and decimal numbers to thousandths.',
    competency: 'Multiply fractions using models.',
    performance_standard: 'Apply operation rules, fractions, and decimals to solve multi-step real-life problems.',
  },
  {
    ref: '5NA-Ic-3',
    domain: 'Number and Algebra',
    content_standard: 'GMDAS, multiplication and division of fractions, and decimal numbers to thousandths.',
    competency: 'Multiply a fraction by a fraction.',
    performance_standard: 'Apply operation rules, fractions, and decimals to solve multi-step real-life problems.',
  },
  {
    ref: '5NA-Ie-1',
    domain: 'Number and Algebra',
    content_standard: 'GMDAS, multiplication and division of fractions, and decimal numbers to thousandths.',
    competency: 'Solve multi-step problems involving multiplication of fractions that may or may not also involve addition or subtraction of fractions.',
    performance_standard: 'Apply operation rules, fractions, and decimals to solve multi-step real-life problems.',
  },
  {
    ref: '5MG-If-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Twelve- and twenty-four-hour time, world time zones, and areas of parallelograms, triangles, and trapezoids.',
    competency: 'Identify the height of a parallelogram, triangle, and trapezoid, in different orientations.',
    performance_standard: 'Use time systems, time zones, and area formulas to solve scheduling and measurement problems.',
  },
  {
    ref: '5MG-If-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Twelve- and twenty-four-hour time, world time zones, and areas of parallelograms, triangles, and trapezoids.',
    competency: 'Find the area of a parallelogram, triangle, and trapezoid, in sq. cm or sq. m, using formulas.',
    performance_standard: 'Use time systems, time zones, and area formulas to solve scheduling and measurement problems.',
  },
  {
    ref: '5MG-If-3',
    domain: 'Measurement and Geometry',
    content_standard: 'Twelve- and twenty-four-hour time, world time zones, and areas of parallelograms, triangles, and trapezoids.',
    competency: 'Estimate the areas of triangles and quadrilaterals (parallelogram, rhombus, trapezoid) using grids.',
    performance_standard: 'Use time systems, time zones, and area formulas to solve scheduling and measurement problems.',
  },
  {
    ref: '5NA-Ih-1',
    domain: 'Number and Algebra',
    content_standard: 'GMDAS, multiplication and division of fractions, and decimal numbers to thousandths.',
    competency: 'Divide fractions using models.',
    performance_standard: 'Apply operation rules, fractions, and decimals to solve multi-step real-life problems.',
  },
  {
    ref: '5NA-Ih-2',
    domain: 'Number and Algebra',
    content_standard: 'GMDAS, multiplication and division of fractions, and decimal numbers to thousandths.',
    competency: 'Divide a fraction by a fraction.',
    performance_standard: 'Apply operation rules, fractions, and decimals to solve multi-step real-life problems.',
  },
  {
    ref: '5NA-Ii-1',
    domain: 'Number and Algebra',
    content_standard: 'GMDAS, multiplication and division of fractions, and decimal numbers to thousandths.',
    competency: 'Solve multi-step problems involving division of fractions that may or may not involve the other operations with fractions.',
    performance_standard: 'Apply operation rules, fractions, and decimals to solve multi-step real-life problems.',
  },
  {
    ref: '5NA-Ij-1',
    domain: 'Number and Algebra',
    content_standard: 'GMDAS, multiplication and division of fractions, and decimal numbers to thousandths.',
    competency: 'Determine: a. The place value to thousandths of a digit in a given decimal number b. The value of a digit c. The digit of a number, given its place value.',
    performance_standard: 'Apply operation rules, fractions, and decimals to solve multi-step real-life problems.',
  },
  {
    ref: '5NA-Ij-2',
    domain: 'Number and Algebra',
    content_standard: 'GMDAS, multiplication and division of fractions, and decimal numbers to thousandths.',
    competency: 'Read and write decimal numbers with decimal parts to thousandths.',
    performance_standard: 'Apply operation rules, fractions, and decimals to solve multi-step real-life problems.',
  },
  {
    ref: '5NA-IIa-1',
    domain: 'Number and Algebra',
    content_standard: 'Decimal operations, divisibility, prime numbers, and composite numbers.',
    competency: 'Convert terminating decimals to fractions, and vice versa.',
    performance_standard: 'Use decimals and number properties to calculate, classify, and solve everyday quantitative problems.',
  },
  {
    ref: '5NA-IIa-2',
    domain: 'Number and Algebra',
    content_standard: 'Decimal operations, divisibility, prime numbers, and composite numbers.',
    competency: 'Compare and order decimal numbers with decimal parts to thousandths.',
    performance_standard: 'Use decimals and number properties to calculate, classify, and solve everyday quantitative problems.',
  },
  {
    ref: '5NA-IIb-1',
    domain: 'Number and Algebra',
    content_standard: 'Decimal operations, divisibility, prime numbers, and composite numbers.',
    competency: 'Round decimal numbers to the nearest thousandths.',
    performance_standard: 'Use decimals and number properties to calculate, classify, and solve everyday quantitative problems.',
  },
  {
    ref: '5NA-IIb-2',
    domain: 'Number and Algebra',
    content_standard: 'Decimal operations, divisibility, prime numbers, and composite numbers.',
    competency: 'Add and subtract decimal numbers with decimal parts of up to 3 decimal places.',
    performance_standard: 'Use decimals and number properties to calculate, classify, and solve everyday quantitative problems.',
  },
  {
    ref: '5NA-IIc-1',
    domain: 'Number and Algebra',
    content_standard: 'Decimal operations, divisibility, prime numbers, and composite numbers.',
    competency: 'Solve multi-step problems involving addition and/or subtraction of decimals, including problems involving money.',
    performance_standard: 'Use decimals and number properties to calculate, classify, and solve everyday quantitative problems.',
  },
  {
    ref: '5NA-IId-1',
    domain: 'Number and Algebra',
    content_standard: 'Decimal operations, divisibility, prime numbers, and composite numbers.',
    competency: 'Use divisibility rules to find common factors of numbers: a. divisibility rules for 2, 5, and 10 b. divisibility rules for 3, 6, and 9 c. divisibility rules for 4, 8, 11, and 12.',
    performance_standard: 'Use decimals and number properties to calculate, classify, and solve everyday quantitative problems.',
  },
  {
    ref: '5NA-IId-2',
    domain: 'Number and Algebra',
    content_standard: 'Decimal operations, divisibility, prime numbers, and composite numbers.',
    competency: 'Distinguish prime numbers from composite numbers using the Sieve of Eratosthenes.',
    performance_standard: 'Use decimals and number properties to calculate, classify, and solve everyday quantitative problems.',
  },
  {
    ref: '5SP-IIf-1',
    domain: 'Statistics and Probability',
    content_standard: 'Bivariate data, double graphs, and theoretical probability of simple events.',
    competency: 'Collects bivariate data from interview, questionnaire, and other appropriate sources.',
    performance_standard: 'Collect and analyze paired data and probability to make informed conclusions in familiar contexts.',
  },
  {
    ref: '5SP-IIf-2',
    domain: 'Statistics and Probability',
    content_standard: 'Bivariate data, double graphs, and theoretical probability of simple events.',
    competency: 'Identify the appropriate graph (bar graph or line graph) to represent a given set of data.',
    performance_standard: 'Collect and analyze paired data and probability to make informed conclusions in familiar contexts.',
  },
  {
    ref: '5SP-IIg-1',
    domain: 'Statistics and Probability',
    content_standard: 'Bivariate data, double graphs, and theoretical probability of simple events.',
    competency: 'Construct double bar graphs and double line graphs.',
    performance_standard: 'Collect and analyze paired data and probability to make informed conclusions in familiar contexts.',
  },
  {
    ref: '5SP-IIg-2',
    domain: 'Statistics and Probability',
    content_standard: 'Bivariate data, double graphs, and theoretical probability of simple events.',
    competency: 'Interpret data presented in a double bar graph or a double line graph.',
    performance_standard: 'Collect and analyze paired data and probability to make informed conclusions in familiar contexts.',
  },
  {
    ref: '5SP-IIg-3',
    domain: 'Statistics and Probability',
    content_standard: 'Bivariate data, double graphs, and theoretical probability of simple events.',
    competency: 'Draw conclusions or make inferences based on data presented in a double bar graph or a double line graph.',
    performance_standard: 'Collect and analyze paired data and probability to make informed conclusions in familiar contexts.',
  },
  {
    ref: '5SP-IIi-1',
    domain: 'Statistics and Probability',
    content_standard: 'Bivariate data, double graphs, and theoretical probability of simple events.',
    competency: 'Solve problems using data presented in a double bar graph or a double line graph.',
    performance_standard: 'Collect and analyze paired data and probability to make informed conclusions in familiar contexts.',
  },
  {
    ref: '5SP-IIj-1',
    domain: 'Statistics and Probability',
    content_standard: 'Bivariate data, double graphs, and theoretical probability of simple events.',
    competency: 'Describe probability as a measure of the chance of an event occurring.',
    performance_standard: 'Collect and analyze paired data and probability to make informed conclusions in familiar contexts.',
  },
  {
    ref: '5SP-IIj-2',
    domain: 'Statistics and Probability',
    content_standard: 'Bivariate data, double graphs, and theoretical probability of simple events.',
    competency: 'Calculate the theoretical probability of a simple event by listing all possible outcomes.',
    performance_standard: 'Collect and analyze paired data and probability to make informed conclusions in familiar contexts.',
  },
  {
    ref: '5NA-IIIa-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division of decimals and mixed operations with fractions and decimals.',
    competency: 'Estimate each of two decimal numbers to the nearest whole number to estimate their product.',
    performance_standard: 'Use decimal and fraction operations to estimate and solve multi-step financial and measurement problems.',
  },
  {
    ref: '5NA-IIIa-2',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division of decimals and mixed operations with fractions and decimals.',
    competency: 'Multiply decimal numbers with decimal parts of up to 2 decimal places.',
    performance_standard: 'Use decimal and fraction operations to estimate and solve multi-step financial and measurement problems.',
  },
  {
    ref: '5NA-IIIa-3',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division of decimals and mixed operations with fractions and decimals.',
    competency: 'Solve multi-step problems involving multiplication of decimals that may or may not also involve addition or subtraction of decimals, including problems involving money.',
    performance_standard: 'Use decimal and fraction operations to estimate and solve multi-step financial and measurement problems.',
  },
  {
    ref: '5NA-IIIc-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division of decimals and mixed operations with fractions and decimals.',
    competency: 'Estimate the quotient when dividing two decimal numbers by estimating the dividend and divisor to the nearest whole number.',
    performance_standard: 'Use decimal and fraction operations to estimate and solve multi-step financial and measurement problems.',
  },
  {
    ref: '5NA-IIIc-2',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division of decimals and mixed operations with fractions and decimals.',
    competency: 'Divide: a. 1- to 2-digit whole numbers resulting in a terminating decimal quotient (e.g., 4 ÷ 5 = 0.8) b. a decimal of up to 2 decimal places by a 1- to 2-digit whole number, resulting in a terminating decimal quotient of up to 3 decimal places.',
    performance_standard: 'Use decimal and fraction operations to estimate and solve multi-step financial and measurement problems.',
  },
  {
    ref: '5NA-IIIc-3',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division of decimals and mixed operations with fractions and decimals.',
    competency: 'Solve multi-step problems involving division of decimals that may or may not also involve the other operations with decimals, including problems involving money.',
    performance_standard: 'Use decimal and fraction operations to estimate and solve multi-step financial and measurement problems.',
  },
  {
    ref: '5NA-IIIe-1',
    domain: 'Number and Algebra',
    content_standard: 'Multiplication and division of decimals and mixed operations with fractions and decimals.',
    competency: 'Perform three or more different operations with fractions and decimals by applying the GMDAS rules.',
    performance_standard: 'Use decimal and fraction operations to estimate and solve multi-step financial and measurement problems.',
  },
  {
    ref: '5MG-IIIf-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Solid figures, nets, surface area, volume, and rotation.',
    competency: 'Illustrate different solid figures using concrete and pictorial models.',
    performance_standard: 'Model and measure solid objects and apply rotation to solve practical spatial problems.',
  },
  {
    ref: '5MG-IIIf-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Solid figures, nets, surface area, volume, and rotation.',
    competency: 'Relate plane figures to solid figures using concrete and pictorial models.',
    performance_standard: 'Model and measure solid objects and apply rotation to solve practical spatial problems.',
  },
  {
    ref: '5MG-IIIg-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Solid figures, nets, surface area, volume, and rotation.',
    competency: 'Describe and differentiate prisms and pyramids using their vertices, faces, and/or edges.',
    performance_standard: 'Model and measure solid objects and apply rotation to solve practical spatial problems.',
  },
  {
    ref: '5MG-IIIg-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Solid figures, nets, surface area, volume, and rotation.',
    competency: 'Illustrate and describe solid figures and their nets.',
    performance_standard: 'Model and measure solid objects and apply rotation to solve practical spatial problems.',
  },
  {
    ref: '5MG-IIIh-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Solid figures, nets, surface area, volume, and rotation.',
    competency: 'Make models of solid figures.',
    performance_standard: 'Model and measure solid objects and apply rotation to solve practical spatial problems.',
  },
  {
    ref: '5MG-IIIh-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Solid figures, nets, surface area, volume, and rotation.',
    competency: 'Illustrate and find the surface area of solid figures.',
    performance_standard: 'Model and measure solid objects and apply rotation to solve practical spatial problems.',
  },
  {
    ref: '5MG-IIIi-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Solid figures, nets, surface area, volume, and rotation.',
    competency: 'Solve problems involving the surface area of solid figures.',
    performance_standard: 'Model and measure solid objects and apply rotation to solve practical spatial problems.',
  },
  {
    ref: '5MG-IIIi-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Solid figures, nets, surface area, volume, and rotation.',
    competency: 'Describe and distinguish cubes and rectangular prisms.',
    performance_standard: 'Model and measure solid objects and apply rotation to solve practical spatial problems.',
  },
  {
    ref: '5MG-IIIj-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Solid figures, nets, surface area, volume, and rotation.',
    competency: 'Estimate the volume of a cube and of a rectangular prism using non-standard units of measurement.',
    performance_standard: 'Model and measure solid objects and apply rotation to solve practical spatial problems.',
  },
  {
    ref: '5MG-IIIj-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Solid figures, nets, surface area, volume, and rotation.',
    competency: 'Draw the image of an object after applying rotation about a point given an angle of rotation, clockwise or counterclockwise.',
    performance_standard: 'Model and measure solid objects and apply rotation to solve practical spatial problems.',
  },
]
