export default [
  {
    ref: '1MG-Ia-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Simple two-dimensional shapes and measurement of length and distance using non-standard units.',
    competency: 'Identify simple 2-dimensional shapes (triangle, rectangle, square) of different size and in different orientation.',
    performance_standard: 'Identify and use shapes and non-standard measures to describe and solve everyday spatial and measurement tasks.',
  },
  {
    ref: '1MG-Ia-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Simple two-dimensional shapes and measurement of length and distance using non-standard units.',
    competency: 'Compare and distinguish 2-dimensional shapes according to features such as sides and corners.',
    performance_standard: 'Identify and use shapes and non-standard measures to describe and solve everyday spatial and measurement tasks.',
  },
  {
    ref: '1MG-Ia-3',
    domain: 'Measurement and Geometry',
    content_standard: 'Simple two-dimensional shapes and measurement of length and distance using non-standard units.',
    competency: 'Compose and decompose triangles, squares, and rectangles.',
    performance_standard: 'Identify and use shapes and non-standard measures to describe and solve everyday spatial and measurement tasks.',
  },
  {
    ref: '1NA-Ib-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100, ordinal numbers up to 10th, and addition with sums up to 20.',
    competency: 'Count up to 100 (includes counting up or down from a given number and identifying a number that is 1 more or 1 less than a given number).',
    performance_standard: 'Use whole numbers, ordinal positions, and addition to represent and solve familiar daily situations.',
  },
  {
    ref: '1NA-Ic-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100, ordinal numbers up to 10th, and addition with sums up to 20.',
    competency: 'Read and write numerals up to 100.',
    performance_standard: 'Use whole numbers, ordinal positions, and addition to represent and solve familiar daily situations.',
  },
  {
    ref: '1NA-Id-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100, ordinal numbers up to 10th, and addition with sums up to 20.',
    competency: 'Recognize and represent numbers up to 100 using a variety of concrete and pictorial models (e.g., number line, block or bar models, and numerals).',
    performance_standard: 'Use whole numbers, ordinal positions, and addition to represent and solve familiar daily situations.',
  },
  {
    ref: '1NA-If-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100, ordinal numbers up to 10th, and addition with sums up to 20.',
    competency: 'Compare two numbers up to 20.',
    performance_standard: 'Use whole numbers, ordinal positions, and addition to represent and solve familiar daily situations.',
  },
  {
    ref: '1NA-If-2',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100, ordinal numbers up to 10th, and addition with sums up to 20.',
    competency: 'Order numbers up to 20 from smallest to largest, and vice versa.',
    performance_standard: 'Use whole numbers, ordinal positions, and addition to represent and solve familiar daily situations.',
  },
  {
    ref: '1NA-If-3',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100, ordinal numbers up to 10th, and addition with sums up to 20.',
    competency: 'Describe the position of objects using ordinal numbers: 1st, 2nd, 3rd, up to 10th.',
    performance_standard: 'Use whole numbers, ordinal positions, and addition to represent and solve familiar daily situations.',
  },
  {
    ref: '1NA-If-4',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100, ordinal numbers up to 10th, and addition with sums up to 20.',
    competency: 'Compose and decompose numbers up to 10 using concrete materials (e.g., 5 is 5 and 0; 4 and 1; 3 and 2; 2 and 3; 1 and 4; 0 and 5).',
    performance_standard: 'Use whole numbers, ordinal positions, and addition to represent and solve familiar daily situations.',
  },
  {
    ref: '1NA-Ih-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100, ordinal numbers up to 10th, and addition with sums up to 20.',
    competency: 'Illustrate addition of numbers with sums up to 20 using a variety of concrete and pictorial models and describes addition as “counting up,” and “putting together.”.',
    performance_standard: 'Use whole numbers, ordinal positions, and addition to represent and solve familiar daily situations.',
  },
  {
    ref: '1NA-Ih-2',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100, ordinal numbers up to 10th, and addition with sums up to 20.',
    competency: 'Illustrate by applying the following properties of addition, using sums up to 20: a. the sum of zero and any number is equal to the number a. changing the order of the addends does not change the sum.',
    performance_standard: 'Use whole numbers, ordinal positions, and addition to represent and solve familiar daily situations.',
  },
  {
    ref: '1NA-Ii-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100, ordinal numbers up to 10th, and addition with sums up to 20.',
    competency: 'Solve problems (given orally or in pictures) involving addition with sums up to 20.',
    performance_standard: 'Use whole numbers, ordinal positions, and addition to represent and solve familiar daily situations.',
  },
  {
    ref: '1MG-Ii-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Simple two-dimensional shapes and measurement of length and distance using non-standard units.',
    competency: 'Measure the length of an object and the distance between two objects using non-standard units.',
    performance_standard: 'Identify and use shapes and non-standard measures to describe and solve everyday spatial and measurement tasks.',
  },
  {
    ref: '1MG-Ij-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Simple two-dimensional shapes and measurement of length and distance using non-standard units.',
    competency: 'Compare lengths and distances using non-standard units.',
    performance_standard: 'Identify and use shapes and non-standard measures to describe and solve everyday spatial and measurement tasks.',
  },
  {
    ref: '1MG-Ij-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Simple two-dimensional shapes and measurement of length and distance using non-standard units.',
    competency: 'Solve problems involving lengths and distances using non-standard units.',
    performance_standard: 'Identify and use shapes and non-standard measures to describe and solve everyday spatial and measurement tasks.',
  },
  {
    ref: '1NA-IIa-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100 and addition and subtraction involving numbers up to 100.',
    competency: 'Order numbers up to 100 from smallest to largest, and vice versa.',
    performance_standard: 'Use place value, addition, and subtraction to solve practical problems involving quantities up to 100.',
  },
  {
    ref: '1NA-IIb-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100 and addition and subtraction involving numbers up to 100.',
    competency: 'Counts by 2s, 5s and 10s up to 100.',
    performance_standard: 'Use place value, addition, and subtraction to solve practical problems involving quantities up to 100.',
  },
  {
    ref: '1NA-IIb-2',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100 and addition and subtraction involving numbers up to 100.',
    competency: 'Determine: a. the place value of a digit in a 2-digit number b. the value of a digit c. the digit of a number, given its place value.',
    performance_standard: 'Use place value, addition, and subtraction to solve practical problems involving quantities up to 100.',
  },
  {
    ref: '1NA-IIc-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100 and addition and subtraction involving numbers up to 100.',
    competency: 'Decompose any 2-digit number into tens and ones.',
    performance_standard: 'Use place value, addition, and subtraction to solve practical problems involving quantities up to 100.',
  },
  {
    ref: '1NA-IIe-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100 and addition and subtraction involving numbers up to 100.',
    competency: 'Add numbers by expressing addends as tens and ones (expanded form).',
    performance_standard: 'Use place value, addition, and subtraction to solve practical problems involving quantities up to 100.',
  },
  {
    ref: '1NA-IIf-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100 and addition and subtraction involving numbers up to 100.',
    competency: 'Add numbers with sums up to 100 without regrouping, using a variety of concrete and pictorial models for: a. 2-digit and 1-digit numbers b. 2-digit and 2-digit numbers.',
    performance_standard: 'Use place value, addition, and subtraction to solve practical problems involving quantities up to 100.',
  },
  {
    ref: '1NA-IIg-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100 and addition and subtraction involving numbers up to 100.',
    competency: 'Solve problems (given orally or in pictures) involving addition with sums up to 100 without regrouping.',
    performance_standard: 'Use place value, addition, and subtraction to solve practical problems involving quantities up to 100.',
  },
  {
    ref: '1SP-IIh-1',
    domain: 'Statistics and Probability',
    content_standard: 'Collection and representation of one-variable data using tables and pictographs without scales.',
    competency: 'Collect data in one variable through a simple interview.',
    performance_standard: 'Collect, organize, present, and interpret simple data from everyday interviews.',
  },
  {
    ref: '1SP-IIh-2',
    domain: 'Statistics and Probability',
    content_standard: 'Collection and representation of one-variable data using tables and pictographs without scales.',
    competency: 'Present data in a pictograph without a scale.',
    performance_standard: 'Collect, organize, present, and interpret simple data from everyday interviews.',
  },
  {
    ref: '1SP-IIh-3',
    domain: 'Statistics and Probability',
    content_standard: 'Collection and representation of one-variable data using tables and pictographs without scales.',
    competency: 'Interpret a pictograph without a scale.',
    performance_standard: 'Collect, organize, present, and interpret simple data from everyday interviews.',
  },
  {
    ref: '1SP-IIh-4',
    domain: 'Statistics and Probability',
    content_standard: 'Collection and representation of one-variable data using tables and pictographs without scales.',
    competency: 'Organize data in a pictograph without a scale into a table.',
    performance_standard: 'Collect, organize, present, and interpret simple data from everyday interviews.',
  },
  {
    ref: '1NA-IIi-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100 and addition and subtraction involving numbers up to 100.',
    competency: 'Illustrate subtraction involving numbers up to 20 using a variety of concrete and pictorial models, and describes subtraction as “taking away.”.',
    performance_standard: 'Use place value, addition, and subtraction to solve practical problems involving quantities up to 100.',
  },
  {
    ref: '1NA-IIi-2',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100 and addition and subtraction involving numbers up to 100.',
    competency: 'Find the missing number in addition or subtraction sentences involving numbers up to 20.',
    performance_standard: 'Use place value, addition, and subtraction to solve practical problems involving quantities up to 100.',
  },
  {
    ref: '1NA-IIi-3',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100 and addition and subtraction involving numbers up to 100.',
    competency: 'Write an equivalent expression to a given addition or subtraction expression (e.g., 2+3 = 1+4; 10-5 = 6-1).',
    performance_standard: 'Use place value, addition, and subtraction to solve practical problems involving quantities up to 100.',
  },
  {
    ref: '1NA-IIj-1',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100 and addition and subtraction involving numbers up to 100.',
    competency: 'Solve subtraction problems (given orally or in pictures) where both numbers are less than 20.',
    performance_standard: 'Use place value, addition, and subtraction to solve practical problems involving quantities up to 100.',
  },
  {
    ref: '1NA-IIj-2',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100 and addition and subtraction involving numbers up to 100.',
    competency: 'Subtract numbers where both numbers are less than 100 using concrete and pictorial models, without regrouping: a. 2-digit minus 1-digit numbers b. 2-digit minus 2-digit numbers.',
    performance_standard: 'Use place value, addition, and subtraction to solve practical problems involving quantities up to 100.',
  },
  {
    ref: '1NA-IIj-3',
    domain: 'Number and Algebra',
    content_standard: 'Whole numbers up to 100 and addition and subtraction involving numbers up to 100.',
    competency: 'Subtract numbers by expressing minuends and subtrahends as tens and ones (expanded form), without regrouping.',
    performance_standard: 'Use place value, addition, and subtraction to solve practical problems involving quantities up to 100.',
  },
  {
    ref: '1NA-IIIa-1',
    domain: 'Number and Algebra',
    content_standard: 'Repeating patterns, halves and quarters, and Philippine money up to ₱100.',
    competency: 'Determine the next term/s in a repeating pattern (patterns could use rhythmic properties, visual elements in the arts, …) (e.g., numbers: 2, 4, 2, 4 , ; letters: a, b, c, a, b, c, a, , ,).',
    performance_standard: 'Use patterns, fractions, and money to describe and solve familiar real-life situations.',
  },
  {
    ref: '1NA-IIIb-1',
    domain: 'Number and Algebra',
    content_standard: 'Repeating patterns, halves and quarters, and Philippine money up to ₱100.',
    competency: 'Create repeating patterns using objects, images, or numbers.',
    performance_standard: 'Use patterns, fractions, and money to describe and solve familiar real-life situations.',
  },
  {
    ref: '1NA-IIIc-1',
    domain: 'Number and Algebra',
    content_standard: 'Repeating patterns, halves and quarters, and Philippine money up to ₱100.',
    competency: 'Illustrate 1/2 and 1/4 as parts of a whole.',
    performance_standard: 'Use patterns, fractions, and money to describe and solve familiar real-life situations.',
  },
  {
    ref: '1NA-IIIc-2',
    domain: 'Number and Algebra',
    content_standard: 'Repeating patterns, halves and quarters, and Philippine money up to ₱100.',
    competency: 'Compare 1/2 and 1/4 using models.',
    performance_standard: 'Use patterns, fractions, and money to describe and solve familiar real-life situations.',
  },
  {
    ref: '1NA-IIId-1',
    domain: 'Number and Algebra',
    content_standard: 'Repeating patterns, halves and quarters, and Philippine money up to ₱100.',
    competency: 'Count halves and quarters.',
    performance_standard: 'Use patterns, fractions, and money to describe and solve familiar real-life situations.',
  },
  {
    ref: '1NA-IIIe-1',
    domain: 'Number and Algebra',
    content_standard: 'Repeating patterns, halves and quarters, and Philippine money up to ₱100.',
    competency: 'Recognize coins (excluding centavo coins) and bills up to ₱100 and their notations.',
    performance_standard: 'Use patterns, fractions, and money to describe and solve familiar real-life situations.',
  },
  {
    ref: '1NA-IIIf-1',
    domain: 'Number and Algebra',
    content_standard: 'Repeating patterns, halves and quarters, and Philippine money up to ₱100.',
    competency: 'Determine the value of a number of bills and/or a number of coins (excluding centavo coins) up to ₱100.',
    performance_standard: 'Use patterns, fractions, and money to describe and solve familiar real-life situations.',
  },
  {
    ref: '1NA-IIIg-1',
    domain: 'Number and Algebra',
    content_standard: 'Repeating patterns, halves and quarters, and Philippine money up to ₱100.',
    competency: 'Compare different denominations of peso coins (excluding centavo coins) and bills up to ₱100.',
    performance_standard: 'Use patterns, fractions, and money to describe and solve familiar real-life situations.',
  },
  {
    ref: '1NA-IIIh-1',
    domain: 'Number and Algebra',
    content_standard: 'Repeating patterns, halves and quarters, and Philippine money up to ₱100.',
    competency: 'Solve 1-step problems (given orally or in pictures) involving addition of money where the sum is up to ₱100, or subtraction of money where both amounts are less than ₱100.',
    performance_standard: 'Use patterns, fractions, and money to describe and solve familiar real-life situations.',
  },
  {
    ref: '1MG-IIIh-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Turns, clock time, days, months, and calendars.',
    competency: 'Identify the position of objects moved in half turn or in quarter turn, in clockwise or in counter-clockwise direction, given an initial facing direction.',
    performance_standard: 'Use direction, clocks, and calendars to describe movement and manage everyday time.',
  },
  {
    ref: '1MG-IIIi-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Turns, clock time, days, months, and calendars.',
    competency: 'Read and write time by the hour, half hour, and quarter hour using an analog clock.',
    performance_standard: 'Use direction, clocks, and calendars to describe movement and manage everyday time.',
  },
  {
    ref: '1MG-IIIi-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Turns, clock time, days, months, and calendars.',
    competency: 'Give the days of the week and months of the year in the correct order.',
    performance_standard: 'Use direction, clocks, and calendars to describe movement and manage everyday time.',
  },
  {
    ref: '1MG-IIIj-1',
    domain: 'Measurement and Geometry',
    content_standard: 'Turns, clock time, days, months, and calendars.',
    competency: 'Determine the day and month of the year using a calendar.',
    performance_standard: 'Use direction, clocks, and calendars to describe movement and manage everyday time.',
  },
  {
    ref: '1MG-IIIj-2',
    domain: 'Measurement and Geometry',
    content_standard: 'Turns, clock time, days, months, and calendars.',
    competency: 'Solve problems involving time (hour, half hour, quarter hour, days in a week, and months in a year).',
    performance_standard: 'Use direction, clocks, and calendars to describe movement and manage everyday time.',
  },
]
